<h1><i class="fa fa-angle-double-right"></i> The Bonded Labour Act </h1>
<p>The object of the Bonded Labour Act is to abolish the Bonded Labour system with a view to preventing the economic & physical exploitation of the weaker sections of the Society.</p>
							
								<h3>Who is Bonded Labour</h3>
								<p>Under section 2 (g) of the Bonded Labour System (Abolition) Act, 1976, the term " bonded labour system " among other things, includes the system of forced, or partly forced, labour under which a debtor enters, or has or is presumed to have, entered into an agreement with the creditor to the effect that in consideration of an advance obtained by him or by any of his lineal ascendants or descendants and in consideration of the interest , if any, due on such advance , or in pursuance of any customary or social obligation or in pursuance of an obligation devolving on him by succession or for any economic consideration received by him or by any of his lineal ascendants or descendants or by reason of his birth in any particular caste or community, he would render by himself or through any member of his family, labour or service to the creditor etc.</p>	
								<h3>Enforcement Machinery</h3>
								<p>The District Magistrate is the authority to ensure the implementation of the provisions of the Act properly. The District Magistrate may appoint an officer subordinate to him who shall  perform all duties &  exercise powers within the local limits so specified. The State Govt. shall constitute Vigilance Committees in each District and Sub-Division to advise the District Magistrate and Sub-Divisional Officer or any Officer authorized by him to ensure that the provisions of the Act or Rules made thereunder are properly implemented.(section-10,12,13)</p>
								
								<h3>What should a person know about the Act ?</h3>
								<p>The District Magistrate & the Officer specified by the District Magistrate shall, as far as practicable try to promote the welfare of the freed bonded labourer by securing and protecting the economic interests so that he may not have any occasion to contract any further bonded debt & shall take such action to eradicate the enforcement of such forced Labour. (section-12)</p>
								<p>The Vigilance Committees shall provide economic & social rehabilitation of freed bonded labourers, coordinate the functions of rural banks and cooperative societies for canalizing adequate credit to freed bonded labourers. (section-13,14)</p>
								<p>The Vigilance Committees shall keep an eye on the number of offences of which cognizance has been taken, to make survey, to defend any suit instituted against a freed bonded labourer or a member of his family or dependent for the recovery of bonded debt. (section-14)</p>
								
								<p>Any custom or tradition or contract, agreement or other instrument whether entered into or executed before or after the commencement of the Act by virtue of which any person or any member of the family or dependent of the such person, is required to do any work or render any service as a bonded labourer, is deemed to be void and inoperative. (section-5)</p>
								
								<p>The Act has also extinguished the liability of the bonded labourer to repay bonded debt. (section-6)</p>
								<p>All property vested in a bonded labourer which was or is under any mortgage ,charge, lien or other encumbrances in connection with any bonded debt is to stand freed and discharged from such mortgage and is to be restored to the possession of such bonded labourer. (section-7)</p>
								<p>No person who has been freed & discharged under this Act from any obligation to render any bonded Labour, is to be evicted from any homestead or other residential promises which he was occupying immediately before the commencement of the Act as part of the consideration for the Bonded Labour. (section-8)</p>
								<p>If any such person has been evicted from such homestead or other residential premises then the same is to be restored as early as practicable to the possession of such bonded laborer, on the complaint of such bonded laborer. (section-8)</p>
								<p>The creditors are also forbidden to accept any payment against any bonded debt which has been extinguished or fully satisfied by virtue of the provisions of the Act. (section-9)</p>
								<p>Whenever any debt is claimed by a Bonded Labourer or Vigilance committee, the burden of proof shall lie on the creditor. (section-9)</p>
								<p>A person who is responsible for enforcing bonded labour, advancement of bonded debt and extracting bonded labour under the bonded labour system, shall be punishable with imprisonment for a term which may extend to three years and also with the fine which may extend to two thousand rupees. (section-16 to 19)</p>