<style>
table, th, td {
  border: 3px  solid silver;
}
tr{
  text-indent: 5px;
   font-size: 12px;
}

</style>
<?php include("HEAD.PHP"); ?>
<body>
	<!-- header-section-starts -->  
     <?php include("top-nav.php"); ?>
		
	<div class="full">
    <div class="col-md-4 top-nav" style="position:relative;background: #464b64;">
			<?php include("left-nav.php"); ?>
		

    <div class="col-md-8 main">
	<br>
	<br>
	<a href="index.php"><b style="margin-right:15px; font-size:20px;font-weight:400; float:right;margin-top:20px;">Go Back</b></a>
	<b><u><h1 style="text-align:center;">Bare Acts</h1></b></u>
	<br>
	<br>

			<table width="80%"style="margin-left:100px;">
  <tr>
    <th width="10%" ><span>Sr. No</span></th>
    <th width="50%" ><span> Title</span></th>
	<th width="20%" ><span>   Download </span>   </th>
  </tr>
<tr> <td>1</td> <td>AIR (PREVENTION AND CONTROL OF POLLUTION) RULES, 1982.pdf</td><td><a  href="msme\300 BARE ACTS\ACCORDING TO THE INDUSTRIAL EMPLOYMENT (STANDING ORDERS) ACT 1946 AND RULES  MADE THEREUNDER.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>AIR (PREVENTION AND CONTROL OF POLLUTION) RULES</a></td></td></tr>
<tr> <td>2</td> <td>AIR FORCE ACT, 1950.pdf</td><td><a  href="msme\300 BARE ACTS\ADMINISTRATION OF EVACUEE PROPERTY (CENTRAL) RULES, 1950.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>AIR FORCE ACT</a></td></td></tr>
<tr> <td>3</td> <td>AIR FORCE RULES, 1969.pdf</td><td><a  href="msme\300 BARE ACTS\ADMINISTRATION OF EVACUEE PROPERTY ACT 1950.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>AIR FORCE RULES</a></td></td></tr>
<tr> <td>4</td> <td>ALL-INDIA SERVICES ACT, 1951.pdf</td><td><a  href="msme\300 BARE ACTS\ADMINISTRATIVE TRIBUNALS ACT, 1985.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ALL-INDIA SERVICES ACT</a></td></td></tr>
<tr> <td>5</td> <td>ANAND MARRIAGE ACT, 1909.pdf</td><td><a  href="msme\300 BARE ACTS\ADVOCATES ACT, 1961.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ANAND MARRIAGE ACT</a></td></td></tr>
<tr> <td>6</td> <td>ANTI-HIJACKING ACT 1982.pdf</td><td><a  href="msme\300 BARE ACTS\AIR (PREVENTION AND CONTROL OF POLLUTION) ACT,1981.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ANTI-HIJACKING AC</a></td></td></tr>
<tr> <td>7</td> <td>ANTIQUITIES AND ART TREASURES ACT, 1972.pdf</td><td><a  href="msme\300 BARE ACTS\AIR (PREVENTION AND CONTROL OF POLLUTION) RULES, 1982.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ANTIQUITIES AND ART TREASURES ACT</a></td></td></tr>
<tr> <td>8</td> <td>ANTIQUITIES AND ART TREASURES RULES 1973.pdf</td><td><a  href="msme\300 BARE ACTS\AIR FORCE ACT, 1950.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ANTIQUITIES AND ART TREASURES RULE</a></td></td></tr>
<tr> <td>9</td> <td>APPRENTICES ACT, 1961.pdf</td><td><a  href="msme\300 BARE ACTS\AIR FORCE RULES, 1969.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>APPRENTICES ACT</a></td></td></tr>
<tr> <td>10</td> <td>APPRENTICESHIP RULES, 1991.pdf</td><td><a  href="msme\300 BARE ACTS\ALL-INDIA SERVICES ACT, 1951.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>APPRENTICESHIP RULES</a></td></td></tr>
<tr> <td>11</td> <td>ARBITRATION AND CONCILIATION ACT,1996.pdf</td><td><a  href="msme\300 BARE ACTS\ANAND MARRIAGE ACT, 1909.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ARBITRATION AND CONCILIATION AC</a></td></td></tr>
<tr> <td>12</td> <td>ARMS ACT, 1959.pdf</td><td><a  href="msme\300 BARE ACTS\ANTI-HIJACKING ACT 1982.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ARMS ACT</a></td></td></tr>
<tr> <td>13</td> <td>ARMS RULES, 1962.pdf</td><td><a  href="msme\300 BARE ACTS\ANTIQUITIES AND ART TREASURES ACT, 1972.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ARMS RULES</a></td></td></tr>
<tr> <td>14</td> <td>ARMY ACT 1950.pdf</td><td><a  href="msme\300 BARE ACTS\ANTIQUITIES AND ART TREASURES RULES 1973.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ARMY AC</a></td></td></tr>
<tr> <td>15</td> <td>ARMY RULES 1954.pdf</td><td><a  href="msme\300 BARE ACTS\APPRENTICES ACT, 1961.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ARMY RULE</a></td></td></tr>
<tr> <td>16</td> <td>ARYA MARRIAGE VALIDATION ACT, 1937.pdf</td><td><a  href="msme\300 BARE ACTS\APPRENTICESHIP RULES, 1991.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ARYA MARRIAGE VALIDATION ACT</a></td></td></tr>
<tr> <td>17</td> <td>BANKERS BOOK EVIDENCE ACT, 1891.pdf</td><td><a  href="msme\300 BARE ACTS\ARBITRATION AND CONCILIATION ACT,1996.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>BANKERS BOOK EVIDENCE ACT</a></td></td></tr>
<tr> <td>18</td> <td>Bankilng  Regulation Rules,1949.pdf</td><td><a  href="msme\300 BARE ACTS\ARMS ACT, 1959.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>Bankilng  Regulation Rule</a></td></td></tr>
<tr> <td>19</td> <td>BANKING REGULATION ACT, 1949.pdf</td><td><a  href="msme\300 BARE ACTS\ARMS RULES, 1962.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>BANKING REGULATION ACT</a></td></td></tr>
<tr> <td>20</td> <td>BAR COUNCIL OF INDIA RULES, 1975.pdf</td><td><a  href="msme\300 BARE ACTS\ARMY ACT 1950.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>BAR COUNCIL OF INDIA RULES</a></td></td></tr>
<tr> <td>21</td> <td>Beedi And Cigar Workers(Condition Of Employment) Act,1966.pdf</td><td><a  href="msme\300 BARE ACTS\ARMY RULES 1954.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>Beedi And Cigar Workers(Condition Of Employment) Ac</a></td></td></tr>
<tr> <td>22</td> <td>BEEDI WORKERS WELFARE FUND RULES, 1978.pdf</td><td><a  href="msme\300 BARE ACTS\ARYA MARRIAGE VALIDATION ACT, 1937.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>BEEDI WORKERS WELFARE FUND RULES</a></td></td></tr>
<tr> <td>23</td> <td>BEEDI WORKERS WELFARE FUND.pdf</td><td><a  href="msme\300 BARE ACTS\BANKERS BOOK EVIDENCE ACT, 1891.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>BEEDI WORKERS WELFAR</a></td></td></tr>
<tr> <td>24</td> <td>BENAMI TRANSACTIONS (PROHIBITION) ACT, 1988.pdf</td><td><a  href="msme\300 BARE ACTS\Bankilng  Regulation Rules,1949.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>BENAMI TRANSACTIONS (PROHIBITION) ACT</a></td></td></tr>
<tr> <td>25</td> <td>BIO-MEDICAL WASTE (MANAGEMENT AND HANDLING) RULES 1998.pdf</td><td><a  href="msme\300 BARE ACTS\BANKING REGULATION ACT, 1949.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>BIO-MEDICAL WASTE (MANAGEMENT AND HANDLING) RULE</a></td></td></tr>
<tr> <td>26</td> <td>BIRTHS, DEATHS AND MARRIAGES REGISTRATION ACT 1886.pdf</td><td><a  href="msme\300 BARE ACTS\BAR COUNCIL OF INDIA RULES, 1975.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>BIRTHS, DEATHS AND MARRIAGES REGISTRATION AC</a></td></td></tr>
<tr> <td>27</td> <td>BONDED LABOUR SYSTEM (ABOLITION) ACT, 1976.pdf</td><td><a  href="msme\300 BARE ACTS\Beedi And Cigar Workers(Condition Of Employment) Act,1966.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>BONDED LABOUR SYSTEM (ABOLITION) ACT</a></td></td></tr>
<tr> <td>28</td> <td>BONDED LABOUR SYSTEM (ABOLITION) RULES 1976.pdf</td><td><a  href="msme\300 BARE ACTS\BEEDI WORKERS WELFARE FUND RULES, 1978.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>BONDED LABOUR SYSTEM (ABOLITION) RULE</a></td></td></tr>
<tr> <td>29</td> <td>BUILDING AND OTHER CONSTRUCTION WORKERS (REGULATION OF EMPLOYMENT AND  CONDITIONS OF SERVICE) ACT, 1996.pdf</td><td><a  href="msme\300 BARE ACTS\BEEDI WORKERS WELFARE FUND.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>BUILDING AND OTHER CONSTRUCTION WORKERS (REGULATION OF EMPLOYMENT AND  CONDITIONS OF SERVICE) ACT</a></td></td></tr>
<tr> <td>30</td> <td>BUREAU OF INDIAN STANDARDS (CERTIFICATION) REGULATIONS, 1988.pdf</td><td><a  href="msme\300 BARE ACTS\BENAMI TRANSACTIONS (PROHIBITION) ACT, 1988.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>BUREAU OF INDIAN STANDARDS (CERTIFICATION) REGULATIONS</a></td></td></tr>
<tr> <td>31</td> <td>BUREAU OF INDIAN STANDARDS ACT, 1986.pdf</td><td><a  href="msme\300 BARE ACTS\BIO-MEDICAL WASTE (MANAGEMENT AND HANDLING) RULES 1998.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>BUREAU OF INDIAN STANDARDS ACT</a></td></td></tr>
<tr> <td>32</td> <td>BUREAU OF INDIAN STANDARDS RULES, 1987.pdf</td><td><a  href="msme\300 BARE ACTS\BIRTHS, DEATHS AND MARRIAGES REGISTRATION ACT 1886.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>BUREAU OF INDIAN STANDARDS RULES</a></td></td></tr>
<tr> <td>33</td> <td>CABLE TELEVISION – NETWORKS (REGULATION) ACT, 1995.pdf</td><td><a  href="msme\300 BARE ACTS\BONDED LABOUR SYSTEM (ABOLITION) ACT, 1976.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CABLE TELEVISION – NETWORKS (REGULATION) ACT</a></td></td></tr>
<tr> <td>34</td> <td>CABLE TELEVISION NETWORKS RULES, 1994.pdf</td><td><a  href="msme\300 BARE ACTS\BONDED LABOUR SYSTEM (ABOLITION) RULES 1976.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CABLE TELEVISION NETWORKS RULES</a></td></td></tr>
<tr> <td>35</td> <td>CANTONMENTS ACT, 1924.pdf</td><td><a  href="msme\300 BARE ACTS\BUILDING AND OTHER CONSTRUCTION WORKERS (REGULATION OF EMPLOYMENT AND  CONDITIONS OF SERVICE) ACT, 1996.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CANTONMENTS ACT</a></td></td></tr>
<tr> <td>36</td> <td>CARRIERS ACT, 1865.pdf</td><td><a  href="msme\300 BARE ACTS\BUREAU OF INDIAN STANDARDS (CERTIFICATION) REGULATIONS, 1988.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CARRIERS ACT</a></td></td></tr>
<tr> <td>37</td> <td>CATTLE-TRESPASS ACT, 1871.pdf</td><td><a  href="msme\300 BARE ACTS\BUREAU OF INDIAN STANDARDS ACT, 1986.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CATTLE-TRESPASS ACT</a></td></td></tr>
<tr> <td>38</td> <td>Central Administrative Tribunal (Procedure) Rules, 1987.pdf</td><td><a  href="msme\300 BARE ACTS\BUREAU OF INDIAN STANDARDS RULES, 1987.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>Central Administrative Tribunal (Procedure) Rules</a></td></td></tr>
<tr> <td>39</td> <td>CENTRAL BOARD FOR THE PREVENTION AND CONTROL OF WA...PROCEDURE FOR TRANSACTION OF BUSINESS) RULES, 1975.pdf</td><td><a  href="msme\300 BARE ACTS\CABLE TELEVISION – NETWORKS (REGULATION) ACT, 1995.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CENTRAL BOARD FOR THE PREVENTION AND CONTROL OF WA...PROCEDURE FOR TRANSACTION OF BUSINESS) RULES</a></td></td></tr>
<tr> <td>40</td> <td>CENTRAL EXERCISE ACT, 1944.pdf</td><td><a  href="msme\300 BARE ACTS\CABLE TELEVISION NETWORKS RULES, 1994.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CENTRAL EXERCISE ACT</a></td></td></tr>
<tr> <td>41</td> <td>CENTRAL MOTOR VEHICLES RULES, 1989.pdf</td><td><a  href="msme\300 BARE ACTS\CANTONMENTS ACT, 1924.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CENTRAL MOTOR VEHICLES RULES</a></td></td></tr>
<tr> <td>42</td> <td>CENTRAL SALES TAX (REGISTRATION & TURNOVER) RULES, 1957.pdf</td><td><a  href="msme\300 BARE ACTS\CARRIERS ACT, 1865.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CENTRAL SALES TAX (REGISTRATION & TURNOVER) RULES</a></td></td></tr>
<tr> <td>43</td> <td>CENTRAL SALES TAX ACT, 1956.pdf</td><td><a  href="msme\300 BARE ACTS\CATTLE-TRESPASS ACT, 1871.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CENTRAL SALES TAX ACT</a></td></td></tr>
<tr> <td>44</td> <td>CENTRAL TRADE UNIONS REGULATIONS, 1938.pdf</td><td><a  href="msme\300 BARE ACTS\Central Administrative Tribunal (Procedure) Rules, 1987.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CENTRAL TRADE UNIONS REGULATIONS</a></td></td></tr>
<tr> <td>45</td> <td>CHARITABLE AND RELIGIOUS TRUSTS ACT, 1920.pdf</td><td><a  href="msme\300 BARE ACTS\CENTRAL BOARD FOR THE PREVENTION AND CONTROL OF WA...PROCEDURE FOR TRANSACTION OF BUSINESS) RULES, 1975.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CHARITABLE AND RELIGIOUS TRUSTS ACT</a></td></td></tr>
<tr> <td>46</td> <td>CHARITABLE ENDOWMENTS ACT, 1890.pdf</td><td><a  href="msme\300 BARE ACTS\CENTRAL EXERCISE ACT, 1944.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CHARITABLE ENDOWMENTS ACT</a></td></td></tr>
<tr> <td>47</td> <td>CHEMICAL ACCIDENTS (EMERGENCY PLANNING, PREPAREDNESS AND RESPONSE) RULES,  1996.pdf</td><td><a  href="msme\300 BARE ACTS\CENTRAL MOTOR VEHICLES RULES, 1989.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CHEMICAL ACCIDENTS (EMERGENCY PLANNING, PREPAREDNESS AND RESPONSE) RULES,</a></td></td></tr>
<tr> <td>48</td> <td>CHILD LABOUR (PROHIBITION AND REGULATION) ACT, 1986.pdf</td><td><a  href="msme\300 BARE ACTS\CENTRAL SALES TAX (REGISTRATION & TURNOVER) RULES, 1957.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CHILD LABOUR (PROHIBITION AND REGULATION) ACT</a></td></td></tr>
<tr> <td>49</td> <td>CHILD LABOUR (PROHIBITION AND REGULATION) RULES, 1988.pdf</td><td><a  href="msme\300 BARE ACTS\CENTRAL SALES TAX ACT, 1956.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CHILD LABOUR (PROHIBITION AND REGULATION) RULES</a></td></td></tr>
<tr> <td>50</td> <td>CHILD MARRIAGE RESTRAINT ACT, 1929.pdf</td><td><a  href="msme\300 BARE ACTS\CENTRAL TRADE UNIONS REGULATIONS, 1938.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CHILD MARRIAGE RESTRAINT ACT</a></td></td></tr>
<tr> <td>51</td> <td>CHILDREN (PLEDGING OF LABOUR) ACT, 1933.pdf</td><td><a  href="msme\300 BARE ACTS\CHARITABLE AND RELIGIOUS TRUSTS ACT, 1920.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CHILDREN (PLEDGING OF LABOUR) ACT</a></td></td></tr>
<tr> <td>52</td> <td>CHILDREN ACT, 1960.pdf</td><td><a  href="msme\300 BARE ACTS\CHARITABLE ENDOWMENTS ACT, 1890.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CHILDREN ACT</a></td></td></tr>
<tr> <td>53</td> <td>CHIT FUNDS ACT, 1982.pdf</td><td><a  href="msme\300 BARE ACTS\CHEMICAL ACCIDENTS (EMERGENCY PLANNING, PREPAREDNESS AND RESPONSE) RULES,  1996.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CHIT FUNDS ACT</a></td></td></tr>
<tr> <td>54</td> <td>CINEMATOGRAPH (CERTIFICATION) RULES, 1983.pdf</td><td><a  href="msme\300 BARE ACTS\CHILD LABOUR (PROHIBITION AND REGULATION) ACT, 1986.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CINEMATOGRAPH (CERTIFICATION) RULES</a></td></td></tr>
<tr> <td>55</td> <td>CINEMATOGRAPH ACT, 1952.pdf</td><td><a  href="msme\300 BARE ACTS\CHILD LABOUR (PROHIBITION AND REGULATION) RULES, 1988.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CINEMATOGRAPH ACT</a></td></td></tr>
<tr> <td>56</td> <td>CINE-WORKERS AND CINEMA THEATRE WORKERS (REGULATION OF EMPLOYMENT) ACT, 1981.pdf</td><td><a  href="msme\300 BARE ACTS\CHILD MARRIAGE RESTRAINT ACT, 1929.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CINE-WORKERS AND CINEMA THEATRE WORKERS (REGULATION OF EMPLOYMENT) ACT</a></td></td></tr>
<tr> <td>57</td> <td>CINE-WORKERS AND CINEMA THEATRE WORKERS (REGULATION OF EMPLOYMENT) RULES,  1984.pdf</td><td><a  href="msme\300 BARE ACTS\CHILDREN (PLEDGING OF LABOUR) ACT, 1933.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CINE-WORKERS AND CINEMA THEATRE WORKERS (REGULATION OF EMPLOYMENT) RULES,</a></td></td></tr>
<tr> <td>58</td> <td>CITIZENSHIP ACT, 1955.pdf</td><td><a  href="msme\300 BARE ACTS\CHILDREN ACT, 1960.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CITIZENSHIP ACT</a></td></td></tr>
<tr> <td>59</td> <td>CITIZENSHIP RULES, 1956.pdf</td><td><a  href="msme\300 BARE ACTS\CHIT FUNDS ACT, 1982.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CITIZENSHIP RULES</a></td></td></tr>
<tr> <td>60</td> <td>CODE OF CRIMINAL PROCEDURE, 1973.pdf</td><td><a  href="msme\300 BARE ACTS\CINEMATOGRAPH (CERTIFICATION) RULES, 1983.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CODE OF CRIMINAL PROCEDURE</a></td></td></tr>
<tr> <td>61</td> <td>COLLECTION OF STATISTICS (CENTRAL) RULES 1959.pdf</td><td><a  href="msme\300 BARE ACTS\CINEMATOGRAPH ACT, 1952.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>COLLECTION OF STATISTICS (CENTRAL) RULE</a></td></td></tr>
<tr> <td>62</td> <td>COLLECTION OF STATISTICS ACT, 1953.pdf</td><td><a  href="msme\300 BARE ACTS\CINE-WORKERS AND CINEMA THEATRE WORKERS (REGULATION OF EMPLOYMENT) ACT, 1981.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>COLLECTION OF STATISTICS ACT</a></td></td></tr>
<tr> <td>63</td> <td>COMMERCIAL DOCUMENTS EVIDENCE ACT, 1939.pdf</td><td><a  href="msme\300 BARE ACTS\CINE-WORKERS AND CINEMA THEATRE WORKERS (REGULATION OF EMPLOYMENT) RULES,  1984.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>COMMERCIAL DOCUMENTS EVIDENCE ACT</a></td></td></tr>
<tr> <td>64</td> <td>COMMISSION OF SATI (PREVENTION) RULES, 1988.pdf</td><td><a  href="msme\300 BARE ACTS\CITIZENSHIP ACT, 1955.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>COMMISSION OF SATI (PREVENTION) RULES</a></td></td></tr>
<tr> <td>65</td> <td>COMMISSIONS OF INQUIRY ACT 1952.pdf</td><td><a  href="msme\300 BARE ACTS\CITIZENSHIP RULES, 1956.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>COMMISSIONS OF INQUIRY AC</a></td></td></tr>
<tr> <td>66</td> <td>COMPANIES ACT 1956.pdf</td><td><a  href="msme\300 BARE ACTS\CODE OF CRIMINAL PROCEDURE, 1973.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>COMPANIES AC</a></td></td></tr>
<tr> <td>67</td> <td>CONSERVATION OF FOREIGN EXCHANGE AND PREVENTION OF   SMUGGLING ACTIVITIES ACT  1974.pdf</td><td><a  href="msme\300 BARE ACTS\COLLECTION OF STATISTICS (CENTRAL) RULES 1959.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CONSERVATION OF FOREIGN EXCHANGE AND PREVENTION OF   SMUGGLING ACTIVITIES ACT</a></td></td></tr>
<tr> <td>68</td> <td>CONSTITUTION OF INDIA.pdf</td><td><a  href="msme\300 BARE ACTS\COLLECTION OF STATISTICS ACT, 1953.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CONSTITUTION OF</a></td></td></tr>
<tr> <td>69</td> <td>CONSUMER PROTECTION ACT, 1986.pdf</td><td><a  href="msme\300 BARE ACTS\COMMERCIAL DOCUMENTS EVIDENCE ACT, 1939.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CONSUMER PROTECTION ACT</a></td></td></tr>
<tr> <td>70</td> <td>CONSUMER PROTECTION RULES, 1987.pdf</td><td><a  href="msme\300 BARE ACTS\COMMISSION OF SATI (PREVENTION) RULES, 1988.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CONSUMER PROTECTION RULES</a></td></td></tr>
<tr> <td>71</td> <td>CONTEMPT OF COURTS ACT, 1971.pdf</td><td><a  href="msme\300 BARE ACTS\COMMISSIONS OF INQUIRY ACT 1952.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CONTEMPT OF COURTS ACT</a></td></td></tr>
<tr> <td>72</td> <td>CONTRACT LABOUR (REGULATION AND ABOLITION) ACT, 1970.pdf</td><td><a  href="msme\300 BARE ACTS\COMPANIES ACT 1956.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CONTRACT LABOUR (REGULATION AND ABOLITION) ACT</a></td></td></tr>
<tr> <td>73</td> <td>CONTRACT LABOUR (REGULATION AND ABOLITION) CENTRAL RULES, 1971.pdf</td><td><a  href="msme\300 BARE ACTS\CONSERVATION OF FOREIGN EXCHANGE AND PREVENTION OF   SMUGGLING ACTIVITIES ACT  1974.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CONTRACT LABOUR (REGULATION AND ABOLITION) CENTRAL RULES</a></td></td></tr>
<tr> <td>74</td> <td>CO-OPERATIVE SOCIETIES ACT, 1912.pdf</td><td><a  href="msme\300 BARE ACTS\CONSTITUTION OF INDIA.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CO-OPERATIVE SOCIETIES ACT</a></td></td></tr>
<tr> <td>75</td> <td>COPY RIGHT ACT, 1957.pdf</td><td><a  href="msme\300 BARE ACTS\CONSUMER PROTECTION ACT, 1986.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>COPY RIGHT ACT</a></td></td></tr>
<tr> <td>76</td> <td>COPYRIGHT RULES, 1958.pdf</td><td><a  href="msme\300 BARE ACTS\CONSUMER PROTECTION RULES, 1987.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>COPYRIGHT RULES</a></td></td></tr>
<tr> <td>77</td> <td>CUSTOMS ACT, 1962.pdf</td><td><a  href="msme\300 BARE ACTS\CONTEMPT OF COURTS ACT, 1971.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>CUSTOMS ACT</a></td></td></tr>
<tr> <td>78</td> <td>DANGEROUS MACHINES (REGULATION) ACT 1983.pdf</td><td><a  href="msme\300 BARE ACTS\CONTRACT LABOUR (REGULATION AND ABOLITION) ACT, 1970.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DANGEROUS MACHINES (REGULATION) AC</a></td></td></tr>
<tr> <td>79</td> <td>DEBTS RECOVERY APPELLATE TRIBUNAL (PROCEDURE) RULES, 1994.pdf</td><td><a  href="msme\300 BARE ACTS\CONTRACT LABOUR (REGULATION AND ABOLITION) CENTRAL RULES, 1971.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DEBTS RECOVERY APPELLATE TRIBUNAL (PROCEDURE) RULES</a></td></td></tr>
<tr> <td>80</td> <td>DEBTS RECOVERY TRIBUNAL (PROCEDURE) RULES, 1993.pdf</td><td><a  href="msme\300 BARE ACTS\CO-OPERATIVE SOCIETIES ACT, 1912.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DEBTS RECOVERY TRIBUNAL (PROCEDURE) RULES</a></td></td></tr>
<tr> <td>81</td> <td>DELHI SHOPS & ESTABLISHMENTS ACT, 1954.pdf</td><td><a  href="msme\300 BARE ACTS\COPY RIGHT ACT, 1957.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DELHI SHOPS & ESTABLISHMENTS ACT</a></td></td></tr>
<tr> <td>82</td> <td>DELHI SPECIAL POLICE ESTABLISHMENT ACT 1946.pdf</td><td><a  href="msme\300 BARE ACTS\COPYRIGHT RULES, 1958.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DELHI SPECIAL POLICE ESTABLISHMENT AC</a></td></td></tr>
<tr> <td>83</td> <td>DEPARTMENTAL INQUIRES (ENFORCEMENT OF ATTENDANCE OF WITNESSES AND  PRODUCTION OF DOCUMENTS) ACT, 1972.pdf</td><td><a  href="msme\300 BARE ACTS\CUSTOMS ACT, 1962.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DEPARTMENTAL INQUIRES (ENFORCEMENT OF ATTENDANCE OF WITNESSES AND  PRODUCTION OF DOCUMENTS) ACT</a></td></td></tr>
<tr> <td>84</td> <td>DISSOLUTION OF MUSLIM MARRIAGES ACT, 1939.pdf</td><td><a  href="msme\300 BARE ACTS\DANGEROUS MACHINES (REGULATION) ACT 1983.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DISSOLUTION OF MUSLIM MARRIAGES ACT</a></td></td></tr>
<tr> <td>85</td> <td>DISTURBED AREAS (SPECIAL COURTS) ACT, 1976.pdf</td><td><a  href="msme\300 BARE ACTS\DEBTS RECOVERY APPELLATE TRIBUNAL (PROCEDURE) RULES, 1994.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DISTURBED AREAS (SPECIAL COURTS) ACT</a></td></td></tr>
<tr> <td>86</td> <td>DOCK WORKERS (REGULATION OF EMPLOYMENT) (INAPPLICABILITY TO MAJOR PORTS) ACT, 1997.pdf</td><td><a  href="msme\300 BARE ACTS\DEBTS RECOVERY TRIBUNAL (PROCEDURE) RULES, 1993.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DOCK WORKERS (REGULATION OF EMPLOYMENT) (INAPPLICABILITY TO MAJOR PORTS) ACT</a></td></td></tr>
<tr> <td>87</td> <td>DOCK WORKERS (REGULATION OF EMPLOYMENT) ACT, 1948.pdf</td><td><a  href="msme\300 BARE ACTS\DELHI SHOPS & ESTABLISHMENTS ACT, 1954.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DOCK WORKERS (REGULATION OF EMPLOYMENT) ACT</a></td></td></tr>
<tr> <td>88</td> <td>DOCK WORKERS (REGULATION OF EMPLOYMENT) RULES, 1962.pdf</td><td><a  href="msme\300 BARE ACTS\DELHI SPECIAL POLICE ESTABLISHMENT ACT 1946.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DOCK WORKERS (REGULATION OF EMPLOYMENT) RULES</a></td></td></tr>
<tr> <td>89</td> <td>DOCK WORKERS (SAFETY, HEALTH AND WELFARE) ACT, 1986.pdf</td><td><a  href="msme\300 BARE ACTS\DEPARTMENTAL INQUIRES (ENFORCEMENT OF ATTENDANCE OF WITNESSES AND  PRODUCTION OF DOCUMENTS) ACT, 1972.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DOCK WORKERS (SAFETY, HEALTH AND WELFARE) ACT</a></td></td></tr>
<tr> <td>90</td> <td>DOWRY PROHIBITION (MAINTENANCE OF LISTS OF PRESENTS TO THE BRIDE AND  BRIDEGROOM) RULES, 1985].pdf</td><td><a  href="msme\300 BARE ACTS\DISSOLUTION OF MUSLIM MARRIAGES ACT, 1939.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DOWRY PROHIBITION (MAINTENANCE OF LISTS OF PRESENTS TO THE BRIDE AND  BRIDEGROOM) RULES,</a></td></td></tr>
<tr> <td>91</td> <td>DOWRY PROHIBITION ACT, 1961.pdf</td><td><a  href="msme\300 BARE ACTS\DISTURBED AREAS (SPECIAL COURTS) ACT, 1976.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DOWRY PROHIBITION ACT</a></td></td></tr>
<tr> <td>92</td> <td>DRAMATIC PERFORMANCES ACT, 1876.pdf</td><td><a  href="msme\300 BARE ACTS\DOCK WORKERS (REGULATION OF EMPLOYMENT) (INAPPLICABILITY TO MAJOR PORTS) ACT, 1997.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DRAMATIC PERFORMANCES ACT</a></td></td></tr>
<tr> <td>93</td> <td>DRUGS (CONTROL) ACT, 1950.pdf</td><td><a  href="msme\300 BARE ACTS\DOCK WORKERS (REGULATION OF EMPLOYMENT) ACT, 1948.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DRUGS (CONTROL) ACT</a></td></td></tr>
<tr> <td>94</td> <td>DRUGS AND COSMETICS ACT, 1940.pdf</td><td><a  href="msme\300 BARE ACTS\DOCK WORKERS (REGULATION OF EMPLOYMENT) RULES, 1962.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DRUGS AND COSMETICS ACT</a></td></td></tr>
<tr> <td>95</td> <td>DRUGS AND MAGIC REMEDIES (OBJECTIONABLE ADVERTISEMENTS) ACT, 1954.pdf</td><td><a  href="msme\300 BARE ACTS\DOCK WORKERS (SAFETY, HEALTH AND WELFARE) ACT, 1986.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>DRUGS AND MAGIC REMEDIES (OBJECTIONABLE ADVERTISEMENTS) ACT</a></td></td></tr>
<tr> <td>96</td> <td>ELECTRICITY (SUPPLY) ACT, 1948.pdf</td><td><a  href="msme\300 BARE ACTS\DOWRY PROHIBITION (MAINTENANCE OF LISTS OF PRESENTS TO THE BRIDE AND  BRIDEGROOM) RULES, 1985].pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ELECTRICITY (SUPPLY) ACT</a></td></td></tr>
<tr> <td>97</td> <td>ELECTRICITY REGULATORY COMMISSIONS ACT, 1998.pdf</td><td><a  href="msme\300 BARE ACTS\DOWRY PROHIBITION ACT, 1961.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ELECTRICITY REGULATORY COMMISSIONS ACT</a></td></td></tr>
<tr> <td>98</td> <td>EMBLEMS AND NAMES (PREVENTION OF IMPROPER USE) ACT, 1950.pdf</td><td><a  href="msme\300 BARE ACTS\DRAMATIC PERFORMANCES ACT, 1876.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EMBLEMS AND NAMES (PREVENTION OF IMPROPER USE) ACT</a></td></td></tr>
<tr> <td>99</td> <td>EMPLOYEES DEPOSIT-LINKED INSURANCE SCHEME, 1976.pdf</td><td><a  href="msme\300 BARE ACTS\DRUGS (CONTROL) ACT, 1950.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EMPLOYEES DEPOSIT-LINKED INSURANCE SCHEME</a></td></td></tr>
<tr> <td>100</td> <td>EMPLOYEES PENSION SCHEME, 1995.pdf</td><td><a  href="msme\300 BARE ACTS\DRUGS AND COSMETICS ACT, 1940.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EMPLOYEES PENSION SCHEME</a></td></td></tr>
<tr> <td>101</td> <td>EMPLOYEES PROVIDENT FUNDS SCHEME, 1952.pdf</td><td><a  href="msme\300 BARE ACTS\DRUGS AND MAGIC REMEDIES (OBJECTIONABLE ADVERTISEMENTS) ACT, 1954.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EMPLOYEES PROVIDENT FUNDS SCHEME</a></td></td></tr>
<tr> <td>102</td> <td>EMPLOYEES STATE INSURANCE (CENTRAL) RULES, 1950.pdf</td><td><a  href="msme\300 BARE ACTS\ELECTRICITY (SUPPLY) ACT, 1948.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EMPLOYEES STATE INSURANCE (CENTRAL) RULES</a></td></td></tr>
<tr> <td>103</td> <td>EMPLOYEES STATE INSURANCE ACT, 1948.pdf</td><td><a  href="msme\300 BARE ACTS\ELECTRICITY REGULATORY COMMISSIONS ACT, 1998.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EMPLOYEES STATE INSURANCE ACT</a></td></td></tr>
<tr> <td>104</td> <td>EMPLOYEES’ PROVIDENT FUNDS AND MISCELLANEOUS PROVISIONS ACT, 1952.pdf</td><td><a  href="msme\300 BARE ACTS\EMBLEMS AND NAMES (PREVENTION OF IMPROPER USE) ACT, 1950.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EMPLOYEES’ PROVIDENT FUNDS AND MISCELLANEOUS PROVISIONS ACT</a></td></td></tr>
<tr> <td>105</td> <td>EMPLOYERS LIABILITY ACT, 1938.pdf</td><td><a  href="msme\300 BARE ACTS\EMPLOYEES DEPOSIT-LINKED INSURANCE SCHEME, 1976.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EMPLOYERS LIABILITY ACT</a></td></td></tr>
<tr> <td>106</td> <td>EMPLOYMENT EXCHANGES (COMPULSORY NOTIFICATION OF VACANCIES) ACT, 1959.pdf</td><td><a  href="msme\300 BARE ACTS\EMPLOYEES PENSION SCHEME, 1995.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EMPLOYMENT EXCHANGES (COMPULSORY NOTIFICATION OF VACANCIES) ACT</a></td></td></tr>
<tr> <td>107</td> <td>EMPLOYMENT EXCHANGES (COMPULSORY NOTIFICATION OF VACANCIES) RULES, 1960.pdf</td><td><a  href="msme\300 BARE ACTS\EMPLOYEES PROVIDENT FUNDS SCHEME, 1952.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EMPLOYMENT EXCHANGES (COMPULSORY NOTIFICATION OF VACANCIES) RULES</a></td></td></tr>
<tr> <td>108</td> <td>EMPLOYMENT OF CHILDREN ACT, 1938.pdf</td><td><a  href="msme\300 BARE ACTS\EMPLOYEES STATE INSURANCE (CENTRAL) RULES, 1950.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EMPLOYMENT OF CHILDREN ACT</a></td></td></tr>
<tr> <td>109</td> <td>EMPLOYMENT OF MANUAL SCAVENGERS AND CONSTRUCTION OF DRY LATRINES  (PROHIBITION) (CENTRAL) RULES, 1997.pdf</td><td><a  href="msme\300 BARE ACTS\EMPLOYEES STATE INSURANCE ACT, 1948.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EMPLOYMENT OF MANUAL SCAVENGERS AND CONSTRUCTION OF DRY LATRINES  (PROHIBITION) (CENTRAL) RULES</a></td></td></tr>
<tr> <td>110</td> <td>ENVIRONMENT (PROTECTION) ACT, 1986.pdf</td><td><a  href="msme\300 BARE ACTS\EMPLOYEES’ PROVIDENT FUNDS AND MISCELLANEOUS PROVISIONS ACT, 1952.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ENVIRONMENT (PROTECTION) ACT</a></td></td></tr>
<tr> <td>111</td> <td>ENVIRONMENT (PROTECTION) RULES, 1986.pdf</td><td><a  href="msme\300 BARE ACTS\EMPLOYERS LIABILITY ACT, 1938.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ENVIRONMENT (PROTECTION) RULES</a></td></td></tr>
<tr> <td>112</td> <td>EQUAL REMUNERATION ACT, 1976.pdf</td><td><a  href="msme\300 BARE ACTS\EMPLOYMENT EXCHANGES (COMPULSORY NOTIFICATION OF VACANCIES) ACT, 1959.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EQUAL REMUNERATION ACT</a></td></td></tr>
<tr> <td>113</td> <td>EQUAL REMUNERATION RULES,1976.pdf</td><td><a  href="msme\300 BARE ACTS\EMPLOYMENT EXCHANGES (COMPULSORY NOTIFICATION OF VACANCIES) RULES, 1960.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EQUAL REMUNERATION RULE</a></td></td></tr>
<tr> <td>114</td> <td>ESSENTIAL COMMODITIES ACT, 1955.pdf</td><td><a  href="msme\300 BARE ACTS\EMPLOYMENT OF CHILDREN ACT, 1938.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ESSENTIAL COMMODITIES ACT</a></td></td></tr>
<tr> <td>115</td> <td>ESSENTIAL SERVICES MAINTENANCE ACT, 1981.pdf</td><td><a  href="msme\300 BARE ACTS\EMPLOYMENT OF MANUAL SCAVENGERS AND CONSTRUCTION OF DRY LATRINES  (PROHIBITION) (CENTRAL) RULES, 1997.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ESSENTIAL SERVICES MAINTENANCE ACT</a></td></td></tr>
<tr> <td>116</td> <td>EXPLOSIVE SUBSTANCES ACT, 1908.pdf</td><td><a  href="msme\300 BARE ACTS\ENVIRONMENT (PROTECTION) ACT, 1986.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EXPLOSIVE SUBSTANCES ACT</a></td></td></tr>
<tr> <td>117</td> <td>EXPLOSIVES ACT, 1884.pdf</td><td><a  href="msme\300 BARE ACTS\ENVIRONMENT (PROTECTION) RULES, 1986.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EXPLOSIVES ACT</a></td></td></tr>
<tr> <td>118</td> <td>EXPLOSIVES RULE, 1983.pdf</td><td><a  href="msme\300 BARE ACTS\EQUAL REMUNERATION ACT, 1976.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>EXPLOSIVES RULE</a></td></td></tr>
<tr> <td>119</td> <td>FACTORIES ACT, 1948.pdf</td><td><a  href="msme\300 BARE ACTS\EQUAL REMUNERATION RULES,1976.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>FACTORIES ACT</a></td></td></tr>
<tr> <td>120</td> <td>FAMILY COURTS ACT, 1984.pdf</td><td><a  href="msme\300 BARE ACTS\ESSENTIAL COMMODITIES ACT, 1955.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>FAMILY COURTS ACT</a></td></td></tr>
<tr> <td>121</td> <td>FATAL ACCIDENTS ACT, 1855.pdf</td><td><a  href="msme\300 BARE ACTS\ESSENTIAL SERVICES MAINTENANCE ACT, 1981.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>FATAL ACCIDENTS ACT</a></td></td></tr>
<tr> <td>122</td> <td>FOREIGN CONTRIBUTION (REGULATION) ACT 1976.pdf</td><td><a  href="msme\300 BARE ACTS\EXPLOSIVE SUBSTANCES ACT, 1908.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>FOREIGN CONTRIBUTION (REGULATION) AC</a></td></td></tr>
<tr> <td>123</td> <td>FOREIGN EXCHANGE MANAGEMENT ACT, 1999].pdf</td><td><a  href="msme\300 BARE ACTS\EXPLOSIVES ACT, 1884.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>FOREIGN EXCHANGE MANAGEMENT ACT,</a></td></td></tr>
<tr> <td>124</td> <td>FOREIGN EXCHANGE REGULATION ACT, 1973.pdf</td><td><a  href="msme\300 BARE ACTS\EXPLOSIVES RULE, 1983.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>FOREIGN EXCHANGE REGULATION ACT</a></td></td></tr>
<tr> <td>125</td> <td>FOREIGN MARRIAGE ACT, 1969.pdf</td><td><a  href="msme\300 BARE ACTS\FACTORIES ACT, 1948.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>FOREIGN MARRIAGE ACT</a></td></td></tr>
<tr> <td>126</td> <td>FOREIGN TRADE (DEVELOPMENT AND REGULATION) ACT, 1992.pdf</td><td><a  href="msme\300 BARE ACTS\FAMILY COURTS ACT, 1984.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>FOREIGN TRADE (DEVELOPMENT AND REGULATION) ACT</a></td></td></tr>
<tr> <td>127</td> <td>FOREIGN TRADE (REGULATION) RULES, 1993.pdf</td><td><a  href="msme\300 BARE ACTS\FATAL ACCIDENTS ACT, 1855.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>FOREIGN TRADE (REGULATION) RULES</a></td></td></tr>
<tr> <td>128</td> <td>FOREIGNERS ACT, 1946.pdf</td><td><a  href="msme\300 BARE ACTS\FOREIGN CONTRIBUTION (REGULATION) ACT 1976.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>FOREIGNERS ACT</a></td></td></tr>
<tr> <td>129</td> <td>FOREST (CONSERVATION) ACT, 1980.pdf</td><td><a  href="msme\300 BARE ACTS\FOREIGN EXCHANGE MANAGEMENT ACT, 1999].pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>FOREST (CONSERVATION) ACT</a></td></td></tr>
<tr> <td>130</td> <td>FOREST (CONSERVATION) RULES, 1981.pdf</td><td><a  href="msme\300 BARE ACTS\FOREIGN EXCHANGE REGULATION ACT, 1973.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>FOREST (CONSERVATION) RULES</a></td></td></tr>
<tr> <td>131</td> <td>GENERAL CLAUSES ACT, 1897.pdf</td><td><a  href="msme\300 BARE ACTS\FOREIGN MARRIAGE ACT, 1969.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>GENERAL CLAUSES ACT</a></td></td></tr>
<tr> <td>132</td> <td>GUARDIANS AND WARDS ACT, 1890.pdf</td><td><a  href="msme\300 BARE ACTS\FOREIGN TRADE (DEVELOPMENT AND REGULATION) ACT, 1992.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>GUARDIANS AND WARDS ACT</a></td></td></tr>
<tr> <td>133</td> <td>HAZARDOUS WASTES (MANAGEMENT AND HANDLING) RULES, 1989.pdf</td><td><a  href="msme\300 BARE ACTS\FOREIGN TRADE (REGULATION) RULES, 1993.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>HAZARDOUS WASTES (MANAGEMENT AND HANDLING) RULES</a></td></td></tr>
<tr> <td>134</td> <td>HINDU ADOPTIONS AND MAINTENANCE ACT, 1956.pdf</td><td><a  href="msme\300 BARE ACTS\FOREIGNERS ACT, 1946.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>HINDU ADOPTIONS AND MAINTENANCE ACT</a></td></td></tr>
<tr> <td>135</td> <td>HINDU DISPOSITION OF PROPERTY ACT, 1916.pdf</td><td><a  href="msme\300 BARE ACTS\FOREST (CONSERVATION) ACT, 1980.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>HINDU DISPOSITION OF PROPERTY ACT</a></td></td></tr>
<tr> <td>136</td> <td>HINDU MINORITY AND GUARDIANSHIP ACT, 1956.pdf</td><td><a  href="msme\300 BARE ACTS\FOREST (CONSERVATION) RULES, 1981.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>HINDU MINORITY AND GUARDIANSHIP ACT</a></td></td></tr>
<tr> <td>137</td> <td>HINDU SUCCESSION ACT, 1956.pdf</td><td><a  href="msme\300 BARE ACTS\GENERAL CLAUSES ACT, 1897.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>HINDU SUCCESSION ACT</a></td></td></tr>
<tr> <td>138</td> <td>HIRE PURCHASE ACT, 1972.pdf</td><td><a  href="msme\300 BARE ACTS\GUARDIANS AND WARDS ACT, 1890.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>HIRE PURCHASE ACT</a></td></td></tr>
<tr> <td>139</td> <td>IDENTIFICATION OF PRISONERS ACTS, 1920.pdf</td><td><a  href="msme\300 BARE ACTS\HAZARDOUS WASTES (MANAGEMENT AND HANDLING) RULES, 1989.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>IDENTIFICATION OF PRISONERS ACTS</a></td></td></tr>
<tr> <td>140</td> <td>IMMORAL TRAFFIC (PREVENTION) ACT, 1956.pdf</td><td><a  href="msme\300 BARE ACTS\HINDU ADOPTIONS AND MAINTENANCE ACT, 1956.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>IMMORAL TRAFFIC (PREVENTION) ACT</a></td></td></tr>
<tr> <td>141</td> <td>INDECENT REPRESENTATION OF WOMEN (PROHIBITION) ACT, 1986.pdf</td><td><a  href="msme\300 BARE ACTS\HINDU DISPOSITION OF PROPERTY ACT, 1916.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDECENT REPRESENTATION OF WOMEN (PROHIBITION) ACT</a></td></td></tr>
<tr> <td>142</td> <td>INDECENT REPRESENTATION OF WOMEN (PROHIBITION) RULES, 1987.pdf</td><td><a  href="msme\300 BARE ACTS\HINDU MINORITY AND GUARDIANSHIP ACT, 1956.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDECENT REPRESENTATION OF WOMEN (PROHIBITION) RULES</a></td></td></tr>
<tr> <td>143</td> <td>INDIAN BOILERS ACT, 1923.pdf</td><td><a  href="msme\300 BARE ACTS\HINDU SUCCESSION ACT, 1956.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN BOILERS ACT</a></td></td></tr>
<tr> <td>144</td> <td>INDIAN CHRISTIAN MARRIAGE ACT, 1872.pdf</td><td><a  href="msme\300 BARE ACTS\HIRE PURCHASE ACT, 1972.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN CHRISTIAN MARRIAGE ACT</a></td></td></tr>
<tr> <td>145</td> <td>INDIAN CONTRACT ACT, 1872.pdf</td><td><a  href="msme\300 BARE ACTS\IDENTIFICATION OF PRISONERS ACTS, 1920.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN CONTRACT ACT</a></td></td></tr>
<tr> <td>146</td> <td>INDIAN DIVORCE ACT, 1869.pdf</td><td><a  href="msme\300 BARE ACTS\IMMORAL TRAFFIC (PREVENTION) ACT, 1956.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN DIVORCE ACT</a></td></td></tr>
<tr> <td>147</td> <td>INDIAN EASEMENTS ACT, 1882.pdf</td><td><a  href="msme\300 BARE ACTS\INDECENT REPRESENTATION OF WOMEN (PROHIBITION) ACT, 1986.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN EASEMENTS ACT</a></td></td></tr>
<tr> <td>148</td> <td>INDIAN ELECTRICITY ACT, 1910.pdf</td><td><a  href="msme\300 BARE ACTS\INDECENT REPRESENTATION OF WOMEN (PROHIBITION) RULES, 1987.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN ELECTRICITY ACT</a></td></td></tr>
<tr> <td>149</td> <td>INDIAN ELECTRICITY RULES, 1956.pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN BOILERS ACT, 1923.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN ELECTRICITY RULES</a></td></td></tr>
<tr> <td>150</td> <td>INDIAN EVIDENCE ACT, 1872.pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN CHRISTIAN MARRIAGE ACT, 1872.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN EVIDENCE ACT</a></td></td></tr>
<tr> <td>151</td> <td>INDIAN FOREST ACT, 1927.pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN CONTRACT ACT, 1872.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN FOREST ACT</a></td></td></tr>
<tr> <td>152</td> <td>INDIAN MAJORITY ACT, 1875.pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN DIVORCE ACT, 1869.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN MAJORITY ACT</a></td></td></tr>
<tr> <td>153</td> <td>INDIAN PARTNERSHIP ACT, 1932.pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN EASEMENTS ACT, 1882.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN PARTNERSHIP ACT</a></td></td></tr>
<tr> <td>154</td> <td>INDIAN PENAL CODE, 1860.pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN ELECTRICITY ACT, 1910.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN PENAL CODE</a></td></td></tr>
<tr> <td>155</td> <td>INDIAN STAMP ACT, 1899.pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN ELECTRICITY RULES, 1956.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN STAMP ACT</a></td></td></tr>
<tr> <td>156</td> <td>INDIAN SUCCESSION ACT, 1925.pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN EVIDENCE ACT, 1872.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN SUCCESSION ACT</a></td></td></tr>
<tr> <td>157</td> <td>INDIAN TRUSTS ACT, 1882..pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN FOREST ACT, 1927.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDIAN TRUSTS ACT,</a></td></td></tr>
<tr> <td>158</td> <td>INDUSTRIAL DISPUTES (CENTRAL) RULES, 1957.pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN MAJORITY ACT, 1875.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDUSTRIAL DISPUTES (CENTRAL) RULES</a></td></td></tr>
<tr> <td>159</td> <td>INDUSTRIAL DISPUTES ACT, 1947.pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN PARTNERSHIP ACT, 1932.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDUSTRIAL DISPUTES ACT</a></td></td></tr>
<tr> <td>160</td> <td>INDUSTRIAL EMPLOYMENT (STANDING ORDERS) ACT, 1946.pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN PENAL CODE, 1860.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDUSTRIAL EMPLOYMENT (STANDING ORDERS) ACT</a></td></td></tr>
<tr> <td>161</td> <td>INDUSTRIES (DEVELOPMENT AND REGULATION) ACT, 1951.pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN STAMP ACT, 1899.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDUSTRIES (DEVELOPMENT AND REGULATION) ACT</a></td></td></tr>
<tr> <td>162</td> <td>INDUSTRLAL EMPLOYMENT (STANDING ORDERS) CENTRAL RULES, 1946.pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN SUCCESSION ACT, 1925.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INDUSTRLAL EMPLOYMENT (STANDING ORDERS) CENTRAL RULES</a></td></td></tr>
<tr> <td>163</td> <td>INFLAMMABLE SUBSTANCES ACT, 1952.pdf</td><td><a  href="msme\300 BARE ACTS\INDIAN TRUSTS ACT, 1882..pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INFLAMMABLE SUBSTANCES ACT</a></td></td></tr>
<tr> <td>164</td> <td>INFORMATION TECHNOLOGY (CERTIFYING AUTHORITIES) RULES, 2000.pdf</td><td><a  href="msme\300 BARE ACTS\INDUSTRIAL DISPUTES (CENTRAL) RULES, 1957.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INFORMATION TECHNOLOGY (CERTIFYING AUTHORITIES) RULES</a></td></td></tr>
<tr> <td>165</td> <td>INFORMATION TECHNOLOGY (CERTIFYING AUTHORITIES) RULES, 2000INFORMATION TECHNOLOGY (CERTIFYING AUTHORITIES) RULES, 2000.pdf</td><td><a  href="msme\300 BARE ACTS\INDUSTRIAL DISPUTES ACT, 1947.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INFORMATION TECHNOLOGY (CERTIFYING AUTHORITIES) RULES, 2000INFORMATION TECHNOLOGY (CERTIFYING AUTHORITIES) RULES</a></td></td></tr>
<tr> <td>166</td> <td>INFORMATION TECHNOLOGY ACT, 2000.pdf</td><td><a  href="msme\300 BARE ACTS\INDUSTRIAL EMPLOYMENT (STANDING ORDERS) ACT, 1946.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INFORMATION TECHNOLOGY ACT</a></td></td></tr>
<tr> <td>167</td> <td>INSURANCE ACT, 1938.pdf</td><td><a  href="msme\300 BARE ACTS\INDUSTRIES (DEVELOPMENT AND REGULATION) ACT, 1951.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INSURANCE ACT</a></td></td></tr>
<tr> <td>168</td> <td>INTERNATIONAL COPYRIGHT ORDER, 1999.pdf</td><td><a  href="msme\300 BARE ACTS\INDUSTRLAL EMPLOYMENT (STANDING ORDERS) CENTRAL RULES, 1946.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INTERNATIONAL COPYRIGHT ORDER</a></td></td></tr>
<tr> <td>169</td> <td>INTER-STATE MIGRANT WORKMEN (REGULATION OF EMPLOYMENT AND CONDITIONS OF  SERVICE) ACT, 1979.pdf</td><td><a  href="msme\300 BARE ACTS\INFLAMMABLE SUBSTANCES ACT, 1952.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INTER-STATE MIGRANT WORKMEN (REGULATION OF EMPLOYMENT AND CONDITIONS OF  SERVICE) ACT</a></td></td></tr>
<tr> <td>170</td> <td>INTER-STATE MIGRANT WORKMEN (REGULATION OF EMPLOYMENT AND CONDITIONS OF  SERVICE) CENTRAL RULES, 1980.pdf</td><td><a  href="msme\300 BARE ACTS\INFORMATION TECHNOLOGY (CERTIFYING AUTHORITIES) RULES, 2000.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>INTER-STATE MIGRANT WORKMEN (REGULATION OF EMPLOYMENT AND CONDITIONS OF  SERVICE) CENTRAL RULES</a></td></td></tr>
<tr> <td>171</td> <td>JUDGES (PROTECTION) ACT, 1985.pdf</td><td><a  href="msme\300 BARE ACTS\INFORMATION TECHNOLOGY (CERTIFYING AUTHORITIES) RULES, 2000INFORMATION TECHNOLOGY (CERTIFYING AUTHORITIES) RULES, 2000.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>JUDGES (PROTECTION) ACT</a></td></td></tr>
<tr> <td>172</td> <td>JUVENILE JUSTICE ACT, 1986.pdf</td><td><a  href="msme\300 BARE ACTS\INFORMATION TECHNOLOGY ACT, 2000.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>JUVENILE JUSTICE ACT</a></td></td></tr>
<tr> <td>173</td> <td>LABOUR LAWS (EXEMPTION FROM FURNISHING RETURNS A…INING REGISTERS BY CERTAIN  ESTABLISHMENTS) ACT, 1988.pdf</td><td><a  href="msme\300 BARE ACTS\INSURANCE ACT, 1938.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>LABOUR LAWS (EXEMPTION FROM FURNISHING RETURNS A…INING REGISTERS BY CERTAIN  ESTABLISHMENTS) ACT</a></td></td></tr>
<tr> <td>174</td> <td>LAND ACQUISITION ACT, 1894.pdf</td><td><a  href="msme\300 BARE ACTS\INTERNATIONAL COPYRIGHT ORDER, 1999.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>LAND ACQUISITION ACT</a></td></td></tr>
<tr> <td>175</td> <td>LEGAL SERVICES AUTHORITIES ACT, 1987.pdf</td><td><a  href="msme\300 BARE ACTS\INTER-STATE MIGRANT WORKMEN (REGULATION OF EMPLOYMENT AND CONDITIONS OF  SERVICE) ACT, 1979.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>LEGAL SERVICES AUTHORITIES ACT</a></td></td></tr>
<tr> <td>176</td> <td>LIMITATION ACT, 1963.pdf</td><td><a  href="msme\300 BARE ACTS\INTER-STATE MIGRANT WORKMEN (REGULATION OF EMPLOYMENT AND CONDITIONS OF  SERVICE) CENTRAL RULES, 1980.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>LIMITATION ACT</a></td></td></tr>
<tr> <td>177</td> <td>MATERNITY BENEFIT ACT, 1961.pdf</td><td><a  href="msme\300 BARE ACTS\JUDGES (PROTECTION) ACT, 1985.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>MATERNITY BENEFIT ACT</a></td></td></tr>
<tr> <td>178</td> <td>MEDICAL TERMINATION OF PREGNANCY ACT, 1971.pdf</td><td><a  href="msme\300 BARE ACTS\JUVENILE JUSTICE ACT, 1986.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>MEDICAL TERMINATION OF PREGNANCY ACT</a></td></td></tr>
<tr> <td>179</td> <td>MEDICAL TERMINATION OF PREGNANCY RULES, 1975.pdf</td><td><a  href="msme\300 BARE ACTS\LABOUR LAWS (EXEMPTION FROM FURNISHING RETURNS A…INING REGISTERS BY CERTAIN  ESTABLISHMENTS) ACT, 1988.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>MEDICAL TERMINATION OF PREGNANCY RULES</a></td></td></tr>
<tr> <td>180</td> <td>MENTAL HEALTH ACT, 1987.pdf</td><td><a  href="msme\300 BARE ACTS\LAND ACQUISITION ACT, 1894.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>MENTAL HEALTH ACT</a></td></td></tr>
<tr> <td>181</td> <td>MINES ACT, 1952.pdf</td><td><a  href="msme\300 BARE ACTS\LEGAL SERVICES AUTHORITIES ACT, 1987.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>MINES ACT</a></td></td></tr>
<tr> <td>182</td> <td>MINES RULES, 1955.pdf</td><td><a  href="msme\300 BARE ACTS\LIMITATION ACT, 1963.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>MINES RULES</a></td></td></tr>
<tr> <td>183</td> <td>MINIMUM WAGES (CENTRAL) RULES, 1950.pdf</td><td><a  href="msme\300 BARE ACTS\MATERNITY BENEFIT ACT, 1961.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>MINIMUM WAGES (CENTRAL) RULES</a></td></td></tr>
<tr> <td>184</td> <td>MINIMUM WAGES ACT, 1948.pdf</td><td><a  href="msme\300 BARE ACTS\MEDICAL TERMINATION OF PREGNANCY ACT, 1971.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>MINIMUM WAGES ACT</a></td></td></tr>
<tr> <td>185</td> <td>MONOPOLIES AND RESTRICTIVE TRADE PRACTICES ACT, 1969.pdf</td><td><a  href="msme\300 BARE ACTS\MEDICAL TERMINATION OF PREGNANCY RULES, 1975.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>MONOPOLIES AND RESTRICTIVE TRADE PRACTICES ACT</a></td></td></tr>
<tr> <td>186</td> <td>MOTOR TRANSPORT WORKERS ACT, 1961.pdf</td><td><a  href="msme\300 BARE ACTS\MENTAL HEALTH ACT, 1987.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>MOTOR TRANSPORT WORKERS ACT</a></td></td></tr>
<tr> <td>187</td> <td>MOTOR VEHICLES ACT, 1988.pdf</td><td><a  href="msme\300 BARE ACTS\MINES ACT, 1952.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>MOTOR VEHICLES ACT</a></td></td></tr>
<tr> <td>188</td> <td>MULTIMODAL TRANSPORTATION OF GOODS ACT, 1993.pdf</td><td><a  href="msme\300 BARE ACTS\MINES RULES, 1955.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>MULTIMODAL TRANSPORTATION OF GOODS ACT</a></td></td></tr>
<tr> <td>189</td> <td>MUSLIM WOMEN (PROTECTION OF RIGHTS ON DIVORCE) ACT, 1986.pdf</td><td><a  href="msme\300 BARE ACTS\MINIMUM WAGES (CENTRAL) RULES, 1950.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>MUSLIM WOMEN (PROTECTION OF RIGHTS ON DIVORCE) ACT</a></td></td></tr>
<tr> <td>190</td> <td>MUSLIM WOMEN (PROTECTION OF RIGHTS ON DIVORCE) RULES, 1986.pdf</td><td><a  href="msme\300 BARE ACTS\MINIMUM WAGES ACT, 1948.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>MUSLIM WOMEN (PROTECTION OF RIGHTS ON DIVORCE) RULES</a></td></td></tr>
<tr> <td>191</td> <td>NATIONAL COMMISSION FOR BACKWARD CLASSES ACT, 1993.pdf</td><td><a  href="msme\300 BARE ACTS\MONOPOLIES AND RESTRICTIVE TRADE PRACTICES ACT, 1969.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>NATIONAL COMMISSION FOR BACKWARD CLASSES ACT</a></td></td></tr>
<tr> <td>192</td> <td>NATIONAL COMMISSION FOR MINORITIES ACT, 1992.pdf</td><td><a  href="msme\300 BARE ACTS\MOTOR TRANSPORT WORKERS ACT, 1961.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>NATIONAL COMMISSION FOR MINORITIES ACT</a></td></td></tr>
<tr> <td>193</td> <td>NATIONAL ENVIRONMENT TRIBUNAL ACT, 1995.pdf</td><td><a  href="msme\300 BARE ACTS\MOTOR VEHICLES ACT, 1988.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>NATIONAL ENVIRONMENT TRIBUNAL ACT</a></td></td></tr>
<tr> <td>194</td> <td>NATIONAL LEGAL SERVICES AUTHORITY RULES, 1995.pdf</td><td><a  href="msme\300 BARE ACTS\MULTIMODAL TRANSPORTATION OF GOODS ACT, 1993.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>NATIONAL LEGAL SERVICES AUTHORITY RULES</a></td></td></tr>
<tr> <td>195</td> <td>NATIONAL SECURITY ACT, 1980.pdf</td><td><a  href="msme\300 BARE ACTS\MUSLIM WOMEN (PROTECTION OF RIGHTS ON DIVORCE) ACT, 1986.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>NATIONAL SECURITY ACT</a></td></td></tr>
<tr> <td>196</td> <td>NEGOTIABLE INSTRUMENTS ACT, 1881.pdf</td><td><a  href="msme\300 BARE ACTS\MUSLIM WOMEN (PROTECTION OF RIGHTS ON DIVORCE) RULES, 1986.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>NEGOTIABLE INSTRUMENTS ACT</a></td></td></tr>
<tr> <td>197</td> <td>NOISE POLLUTION (REGULATION AND CONTROL) RULES, 2000.pdf</td><td><a  href="msme\300 BARE ACTS\NATIONAL COMMISSION FOR BACKWARD CLASSES ACT, 1993.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>NOISE POLLUTION (REGULATION AND CONTROL) RULES</a></td></td></tr>
<tr> <td>198</td> <td>NOTARIES ACT, 1952.pdf</td><td><a  href="msme\300 BARE ACTS\NATIONAL COMMISSION FOR MINORITIES ACT, 1992.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>NOTARIES ACT</a></td></td></tr>
<tr> <td>199</td> <td>NOTARIES RULES, 1956.pdf</td><td><a  href="msme\300 BARE ACTS\NATIONAL ENVIRONMENT TRIBUNAL ACT, 1995.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>NOTARIES RULES</a></td></td></tr>
<tr> <td>200</td> <td>OATHS ACT, 1969.pdf</td><td><a  href="msme\300 BARE ACTS\NATIONAL LEGAL SERVICES AUTHORITY RULES, 1995.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>OATHS ACT</a></td></td></tr>
<tr> <td>201</td> <td>OFFICIAL SECRETS ACT, 1923.pdf</td><td><a  href="msme\300 BARE ACTS\NATIONAL SECURITY ACT, 1980.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>OFFICIAL SECRETS ACT</a></td></td></tr>
<tr> <td>202</td> <td>OFFICIAL TRUSTEES ACT, 1913.pdf</td><td><a  href="msme\300 BARE ACTS\NEGOTIABLE INSTRUMENTS ACT, 1881.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>OFFICIAL TRUSTEES ACT</a></td></td></tr>
<tr> <td>203</td> <td>PARSI MARRIAGE AND DIVORCE ACT, 1936.pdf</td><td><a  href="msme\300 BARE ACTS\NOISE POLLUTION (REGULATION AND CONTROL) RULES, 2000.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PARSI MARRIAGE AND DIVORCE ACT</a></td></td></tr>
<tr> <td>204</td> <td>PARTITION ACT, 1893.pdf</td><td><a  href="msme\300 BARE ACTS\NOTARIES ACT, 1952.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PARTITION ACT</a></td></td></tr>
<tr> <td>205</td> <td>PASSPORT ENTRY INTO INDIA ACT, 1920.pdf</td><td><a  href="msme\300 BARE ACTS\NOTARIES RULES, 1956.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PASSPORT ENTRY INTO INDIA ACT</a></td></td></tr>
<tr> <td>206</td> <td>PASSPORT RULES, 1980.pdf</td><td><a  href="msme\300 BARE ACTS\OATHS ACT, 1969.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PASSPORT RULES</a></td></td></tr>
<tr> <td>207</td> <td>PASSPORTS ACT, 1967.pdf</td><td><a  href="msme\300 BARE ACTS\OFFICIAL SECRETS ACT, 1923.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PASSPORTS ACT</a></td></td></tr>
<tr> <td>208</td> <td>PATENTS ACT, 1970.pdf</td><td><a  href="msme\300 BARE ACTS\OFFICIAL TRUSTEES ACT, 1913.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PATENTS ACT</a></td></td></tr>
<tr> <td>209</td> <td>PATENTS RULES,1972.pdf</td><td><a  href="msme\300 BARE ACTS\PARSI MARRIAGE AND DIVORCE ACT, 1936.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PATENTS RULE</a></td></td></tr>
<tr> <td>210</td> <td>PAYMENT OF BONUS ACT, 1965.pdf</td><td><a  href="msme\300 BARE ACTS\PARTITION ACT, 1893.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PAYMENT OF BONUS ACT</a></td></td></tr>
<tr> <td>211</td> <td>PAYMENT OF BONUS RULES, 1975.pdf</td><td><a  href="msme\300 BARE ACTS\PASSPORT ENTRY INTO INDIA ACT, 1920.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PAYMENT OF BONUS RULES</a></td></td></tr>
<tr> <td>212</td> <td>PAYMENT OF GRATUITY (CENTRAL) RULES, 1972.pdf</td><td><a  href="msme\300 BARE ACTS\PASSPORT RULES, 1980.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PAYMENT OF GRATUITY (CENTRAL) RULES</a></td></td></tr>
<tr> <td>213</td> <td>PAYMENT OF GRATUTY ACT, 1972.pdf</td><td><a  href="msme\300 BARE ACTS\PASSPORTS ACT, 1967.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PAYMENT OF GRATUTY ACT</a></td></td></tr>
<tr> <td>214</td> <td>PAYMENT OF WAGES (PROCEDURE) RULES, 1937.pdf</td><td><a  href="msme\300 BARE ACTS\PATENTS ACT, 1970.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PAYMENT OF WAGES (PROCEDURE) RULES</a></td></td></tr>
<tr> <td>215</td> <td>PERSONAL INJURIES (EMERGENCY PROVISIONS) ACT, 1962.pdf</td><td><a  href="msme\300 BARE ACTS\PATENTS RULES,1972.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PERSONAL INJURIES (EMERGENCY PROVISIONS) ACT</a></td></td></tr>
<tr> <td>216</td> <td>PLACES OF WORSHIP (SPECIAL PROVISIONS) ACT, 1991.pdf</td><td><a  href="msme\300 BARE ACTS\PAYMENT OF BONUS ACT, 1965.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PLACES OF WORSHIP (SPECIAL PROVISIONS) ACT</a></td></td></tr>
<tr> <td>217</td> <td>PLANTATIONS LABOUR ACT, 1951.pdf</td><td><a  href="msme\300 BARE ACTS\PAYMENT OF BONUS RULES, 1975.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PLANTATIONS LABOUR ACT</a></td></td></tr>
<tr> <td>218</td> <td>POISONS ACT, 1919.pdf</td><td><a  href="msme\300 BARE ACTS\PAYMENT OF GRATUITY (CENTRAL) RULES, 1972.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>POISONS ACT</a></td></td></tr>
<tr> <td>219</td> <td>POLICE (INCITEMENT TO DISAFFECTION) ACT, 1922.pdf</td><td><a  href="msme\300 BARE ACTS\PAYMENT OF GRATUTY ACT, 1972.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>POLICE (INCITEMENT TO DISAFFECTION) ACT</a></td></td></tr>
<tr> <td>220</td> <td>POLICE ACT, 1861.pdf</td><td><a  href="msme\300 BARE ACTS\PAYMENT OF WAGES (PROCEDURE) RULES, 1937.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>POLICE ACT</a></td></td></tr>
<tr> <td>221</td> <td>POLICE ACT, 1888.pdf</td><td><a  href="msme\300 BARE ACTS\PERSONAL INJURIES (EMERGENCY PROVISIONS) ACT, 1962.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>POLICE ACT</a></td></td></tr>
<tr> <td>222</td> <td>POLICE ACT, 1949.pdf</td><td><a  href="msme\300 BARE ACTS\PLACES OF WORSHIP (SPECIAL PROVISIONS) ACT, 1991.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>POLICE ACT</a></td></td></tr>
<tr> <td>223</td> <td>POLICE FORCES (RESTRICTIONS OF RIGHTS) ACT, 1966.pdf</td><td><a  href="msme\300 BARE ACTS\PLANTATIONS LABOUR ACT, 1951.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>POLICE FORCES (RESTRICTIONS OF RIGHTS) ACT</a></td></td></tr>
<tr> <td>224</td> <td>POLLUTION) (UNION TERRITORIES) RULES, 1983.pdf</td><td><a  href="msme\300 BARE ACTS\POISONS ACT, 1919.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>POLLUTION) (UNION TERRITORIES) RULES</a></td></td></tr>
<tr> <td>225</td> <td>POWERS OF ATTORNEY ACT, 1882.pdf</td><td><a  href="msme\300 BARE ACTS\POLICE (INCITEMENT TO DISAFFECTION) ACT, 1922.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>POWERS OF ATTORNEY ACT</a></td></td></tr>
<tr> <td>226</td> <td>PREVENTION OF CORRUPTION ACT, 1988.pdf</td><td><a  href="msme\300 BARE ACTS\POLICE ACT, 1861.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PREVENTION OF CORRUPTION ACT</a></td></td></tr>
<tr> <td>227</td> <td>PREVENTION OF CRUELTY TO ANIMALS ACT, 1960.pdf</td><td><a  href="msme\300 BARE ACTS\POLICE ACT, 1888.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PREVENTION OF CRUELTY TO ANIMALS ACT</a></td></td></tr>
<tr> <td>228</td> <td>PREVENTION OF DAMAGE TO PUBLIC PROPERTY ACT, 1984.pdf</td><td><a  href="msme\300 BARE ACTS\POLICE ACT, 1949.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PREVENTION OF DAMAGE TO PUBLIC PROPERTY ACT</a></td></td></tr>
<tr> <td>229</td> <td>PREVENTION OF FOOD ADULTERATION ACT, 1954.pdf</td><td><a  href="msme\300 BARE ACTS\POLICE FORCES (RESTRICTIONS OF RIGHTS) ACT, 1966.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PREVENTION OF FOOD ADULTERATION ACT</a></td></td></tr>
<tr> <td>230</td> <td>PREVENTION OF FOOD ADULTERATION RULES, 1955.pdf</td><td><a  href="msme\300 BARE ACTS\POLLUTION) (UNION TERRITORIES) RULES, 1983.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PREVENTION OF FOOD ADULTERATION RULES</a></td></td></tr>
<tr> <td>231</td> <td>PREVENTION OF ILLICIT TRAFFIC IN NARCOTIC DRUGS AND PSYCHOTROPIC SUBSTANCES  ACT, 1988.pdf</td><td><a  href="msme\300 BARE ACTS\POWERS OF ATTORNEY ACT, 1882.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PREVENTION OF ILLICIT TRAFFIC IN NARCOTIC DRUGS AND PSYCHOTROPIC SUBSTANCES  ACT</a></td></td></tr>
<tr> <td>232</td> <td>PREVENTION OF INSULTS TO NATIONAL HONOUR ACT, 1971.pdf</td><td><a  href="msme\300 BARE ACTS\PREVENTION OF CORRUPTION ACT, 1988.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PREVENTION OF INSULTS TO NATIONAL HONOUR ACT</a></td></td></tr>
<tr> <td>233</td> <td>PREVENTION OF SEDITIOUS MEETINGS ACT, 1911.pdf</td><td><a  href="msme\300 BARE ACTS\PREVENTION OF CRUELTY TO ANIMALS ACT, 1960.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PREVENTION OF SEDITIOUS MEETINGS ACT</a></td></td></tr>
<tr> <td>234</td> <td>PRISONERS (ATTENDANCE IN COURTS) ACT, 1955.pdf</td><td><a  href="msme\300 BARE ACTS\PREVENTION OF DAMAGE TO PUBLIC PROPERTY ACT, 1984.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>PRISONERS (ATTENDANCE IN COURTS) ACT</a></td></td></tr>
<tr> <td>235</td> <td>THE HINDU MARRIAGE ACT, 1955.pdf</td><td><a  href="msme\300 BARE ACTS\PREVENTION OF FOOD ADULTERATION ACT, 1954.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>THE HINDU MARRIAGE ACT</a></td></td></tr>
<tr> <td>236</td> <td>THE INDIAN TELEGRAPH ACT, 1885.pdf</td><td><a  href="msme\300 BARE ACTS\PREVENTION OF FOOD ADULTERATION RULES, 1955.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>THE INDIAN TELEGRAPH ACT</a></td></td></tr>
<tr> <td>237</td> <td>THE INDIAN WIRELESS TELEGRAPHY ACT, 1933.pdf</td><td><a  href="msme\300 BARE ACTS\PREVENTION OF ILLICIT TRAFFIC IN NARCOTIC DRUGS AND PSYCHOTROPIC SUBSTANCES  ACT, 1988.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>THE INDIAN WIRELESS TELEGRAPHY ACT</a></td></td></tr>
<tr> <td>238</td> <td>THE INTEREST ACT, 1978.pdf</td><td><a  href="msme\300 BARE ACTS\PREVENTION OF INSULTS TO NATIONAL HONOUR ACT, 1971.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>THE INTEREST ACT</a></td></td></tr>
<tr> <td>239</td> <td>The Muslim Personal Law (SHARIAT) APPLICATION ACT, 1937.pdf</td><td><a  href="msme\300 BARE ACTS\PREVENTION OF SEDITIOUS MEETINGS ACT, 1911.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>The Muslim Personal Law (SHARIAT) APPLICATION ACT</a></td></td></tr>
<tr> <td>240</td> <td>THE NATIONAL COMMMISSION FOR WOMEN ACT, 1990.pdf</td><td><a  href="msme\300 BARE ACTS\PRISONERS (ATTENDANCE IN COURTS) ACT, 1955.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>THE NATIONAL COMMMISSION FOR WOMEN ACT</a></td></td></tr>
<tr> <td>241</td> <td>ACCORDING TO THE INDUSTRIAL EMPLOYMENT (STANDING ORDERS) ACT 1946 AND RULES  MADE THEREUNDER.pdf</td><td><a  href="msme\300 BARE ACTS\THE HINDU MARRIAGE ACT, 1955.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ACCORDING TO THE INDUSTRIAL EMPLOYMENT (STANDING ORDERS) ACT 1946 AND RULES  MADE THER</a></td></td></tr>
<tr> <td>242</td> <td>ADMINISTRATION OF EVACUEE PROPERTY (CENTRAL) RULES, 1950.pdf</td><td><a  href="msme\300 BARE ACTS\THE INDIAN TELEGRAPH ACT, 1885.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ADMINISTRATION OF EVACUEE PROPERTY (CENTRAL) RULES</a></td></td></tr>
<tr> <td>243</td> <td>ADMINISTRATION OF EVACUEE PROPERTY ACT 1950.pdf</td><td><a  href="msme\300 BARE ACTS\THE INDIAN WIRELESS TELEGRAPHY ACT, 1933.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ADMINISTRATION OF EVACUEE PROPERTY AC</a></td></td></tr>
<tr> <td>244</td> <td>ADMINISTRATIVE TRIBUNALS ACT, 1985.pdf</td><td><a  href="msme\300 BARE ACTS\THE INTEREST ACT, 1978.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ADMINISTRATIVE TRIBUNALS ACT</a></td></td></tr>
<tr> <td>245</td> <td>ADVOCATES ACT, 1961.pdf</td><td><a  href="msme\300 BARE ACTS\The Muslim Personal Law (SHARIAT) APPLICATION ACT, 1937.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>ADVOCATES ACT</a></td></td></tr>
<tr> <td>246</td> <td>AIR (PREVENTION AND CONTROL OF POLLUTION) ACT,1981.pdf</td><td><a  href="msme\300 BARE ACTS\THE NATIONAL COMMMISSION FOR WOMEN ACT, 1990.pdf" target="_blank"><img class="pdfIcon" src="images/file-pdf.jpg" alt="Acts" width="20" height="20"/>AIR (PREVENTION AND CONTROL OF POLLUTION) AC</a></td></td></tr>

</table>
<div class="clearfix"> </div>
	<!--/footer-->
	<?php include("footer.php"); ?>