	<html>
<?php //include("api.php"); ?>
<?php include("HEAD.PHP"); ?>
<body>
	<!-- header-section-starts -->  
     <?php include("top-nav.php"); ?>
		
	<div class="full">
    <div class="col-md-4 top-nav" style="position:relative; background: #464B64;">
			<?php include("left-nav.php"); ?>
		<!--banner-section-->
	<div class="col-md-8 main"><br>
	<br>
<a href="index.php"><b style="margin-right:15px; font-size:20px;font-weight:400; float:right;margin-top:20px;">Go Back</b></a><h1 class="Default" style="text-align: center;">&nbsp;<strong style="font-size: normal; text-align: center;"><span style="color: #ff0000;"><span style="font-size: normal;">Registration Under FCRA</span></span></strong></h1> <p style="text-align: justify; padding:5"><br /><span style="font-size: small;"><strong><span style="color: #ff0000;">FCRA Registration</span> </strong></span><br />Foreign Contribution Regulation Act was established in the year 1976 in order to regulate and control the foreign currency or wealth received by individuals working in different areas of national life. FCRA registration is mandatory for not to utilize the foreign money for influencing voters in a public poll or election. FCRA registration in India is done by many leading legal firms and professionals in order to avoid any disputes in future regarding this registration. To organize religious, cultural and social events and performances organizations need FCRA registration from the Government of India through an FCRA application form duly signed by the institution and agent or attorney. There online FCRA registration has been growing immensely due to its easy and smooth process. FCRA registration is not meant for all organizations as it was only for those who have some proven track records of organizing some social events and have audited accounts for more than three years by the certified auditors</p> <p class="Default"><span style="color: #ff0000;"><strong><br /></strong></span></p> <p class="Default"><span style="color: #ff0000;"><strong>CONTACT US</strong></span></p> <p class="Default"><span>K.BEHARI &amp; ASSOCIATES</span></p> <p class="Default"><span>[Project Consultants]</span></p> <p class="Default"><span>Kunj Behari Mahipal</span></p> <p class="Default"><span>C.Shekhar Mahipal (B.Com, LL.B Advocate)</span></p> <p class="Default"><span>ANAND SHANKER &amp; COMPANY</span></p> <p class="Default"><span>[Chartered Accountants]</span></p> <p class="Default"><span>CA. Anand Shanker Mahipal</span></p> <p class="Default"><span>&nbsp;</span></p> <p class="Default"><span style="color: #ff0000;"><strong>Contact Info:</strong></span></p> <p class="Default"><span>Mailing Address:</span></p> <p class="Default"><span>&ldquo;DGM Building&rdquo; Old Court Road, Near Railway Crossing SIRSA-125055 (HARYANA) INDIA</span></p> <p class="Default"><span><em>Phones &amp; Mobiles:&nbsp;</em>Phone: +91(1666) 232543, 234565, 234022 Mobile: +91-9416-351-167, 9050-902-425</span></p> <p class="Default"><span><em>Emails:</em></span></p> <p class="Default"><span>Kboffice.india@gmail.com</span></p> <p class="Default"><span>kbaconsultants@hotmail.com</span></p> <p><span>ca.anand@hotmail.com</span></p><div class="clearfix"> </div>
	<!--/footer-->
	<?php include("footer.php"); ?>