<?php include("main.php"); ?>
<h1><center> Haryana State Acts and Rules</center></h1>
<br>
<br>
<table class="end" width="80%">
  <tr>
    <th width="10%" ><span>Sr. No</span></th>
    <th width="50%" ><span> Title</span></th>
	<th width="20%" ><span>   Download </span>   </th>
  </tr>

<tr><td>	1	</td><td>	Haryanan State Acts	</td><td>	<a href="	act\HARYANA STATE ACT\	Haryanan State Acts.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	2	</td><td>	The Indian Registration (Punjab Amendment) Act, 1961	</td><td>	<a href="	act\HARYANA STATE ACT\	The Indian Registration (Punjab Amendment) Act, 1961.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	3	</td><td>	The Code of Criminal Procedure	</td><td>	<a href="	act\HARYANA STATE ACT\	1.The Code of Criminal Procedure.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	4	</td><td>	The Court Fees Act, 1870	</td><td>	<a href="	act\HARYANA STATE ACT\	2.The Court Fees Act, 1870.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	5	</td><td>	The Criminal Law Amendment (Extension) Act, 1957	</td><td>	<a href="	act\HARYANA STATE ACT\	3.The Criminal Law Amendment (Extension) Act, 1957.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	6	</td><td>	The Damaged Areas (Disposal of Debris) Rules, 1950	</td><td>	<a href="	act\HARYANA STATE ACT\	4.The Damaged Areas (Disposal of Debris) Rules, 1950.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	7	</td><td>	Displaced Persons (Compensation and Rehabilitation) Act, 1954	</td><td>	<a href="	act\HARYANA STATE ACT\	5.Displaced Persons (Compensation and Rehabilitation) Act, 1954.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	8	</td><td>	The East Punjab Agricultural Pests, Diseases and Noxious Weeds Act, 1949	</td><td>	<a href="	act\HARYANA STATE ACT\	6.The East Punjab Agricultural Pests, Diseases and Noxious Weeds Act, 1949.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	9	</td><td>	East Punjab Cement Control (Repealing) Act, 1962	</td><td>	<a href="	act\HARYANA STATE ACT\	7.East Punjab Cement Control (Repealing) Act, 1962.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	10	</td><td>	The East Punjab Conservation of Firewood Supplies Act, 1949	</td><td>	<a href="	act\HARYANA STATE ACT\	8.The East Punjab Conservation of Firewood Supplies Act, 1949.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	11	</td><td>	The East Punjab Conservation of Manure Act, 1949	</td><td>	<a href="	act\HARYANA STATE ACT\	9.The East Punjab Conservation of Manure Act, 1949.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	12	</td><td>	East Punjab Control of Bricks Supplies Act, 1949	</td><td>	<a href="	act\HARYANA STATE ACT\	10.East Punjab Control of Bricks Supplies Act, 1949.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	13	</td><td>	The East Punjab Drugs (Control) Act, 1949	</td><td>	<a href="	act\HARYANA STATE ACT\	11.The East Punjab Drugs (Control) Act, 1949.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	14	</td><td>	The East Punjab Enumeration of Dwellings Act, 1948	</td><td>	<a href="	act\HARYANA STATE ACT\	12.The East Punjab Enumeration of Dwellings Act, 1948.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	15	</td><td>	The East Punjab Extension of Limitation Act, 1947	</td><td>	<a href="	act\HARYANA STATE ACT\	13.The East Punjab Extension of Limitation Act, 1947.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	16	</td><td>	The East Punjab Factories (Control of Dismantling) Act, 1948	</td><td>	<a href="	act\HARYANA STATE ACT\	14.The East Punjab Factories (Control of Dismantling) Act, 1948.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	17	</td><td>	The East Punjab Holdings (Consolidation and Prevention of Fragmentation) Act, 1948	</td><td>	<a href="	act\HARYANA STATE ACT\	15.The East Punjab Holdings (Consolidation and Prevention of Fragmentation) Act, 1948.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	18	</td><td>	The East Punjab Holdings (Consolidation and Prevention of Fragmentation) Haryana Validation Act, 1971	</td><td>	<a href="	act\HARYANA STATE ACT\	16.The East Punjab Holdings (Consolidation and Prevention of Fragmentation) Haryana Validation Act, 1971.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	19	</td><td>	East Punjab Improved Seeds and Seedlings Act, 1949	</td><td>	<a href="	act\HARYANA STATE ACT\	17.East Punjab Improved Seeds and Seedlings Act, 1949.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	20	</td><td>	The East Punjab Local Authorities (Restriction of Functions) Act, 1947	</td><td>	<a href="	act\HARYANA STATE ACT\	18.The East Punjab Local Authorities (Restriction of Functions) Act, 1947.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	21	</td><td>	The East Punjab Molasses (Control) Act, 1948	</td><td>	<a href="	act\HARYANA STATE ACT\	19.The East Punjab Molasses (Control) Act, 1948.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	22	</td><td>	The Electricity (Supply) (Punjab Amendment) Act, 1959	</td><td>	<a href="	act\HARYANA STATE ACT\	20.The Electricity (Supply) (Punjab Amendment) Act, 1959.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	23	</td><td>	The Electricity (Supply) (Punjab Amendment) Act, 1961	</td><td>	<a href="	act\HARYANA STATE ACT\	21.The Electricity (Supply) (Punjab Amendment) Act, 1961.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	24	</td><td>	The Essential Commodities (Punjab Amendment) Act, 1959	</td><td>	<a href="	act\HARYANA STATE ACT\	22.The Essential Commodities (Punjab Amendment) Act, 1959.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	25	</td><td>	Estate Management Procedure, 2005	</td><td>	<a href="	act\HARYANA STATE ACT\	23.Estate Management Procedure, 2005.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	26	</td><td>	The Factories (Haryana) Exempting Rules, 1980	</td><td>	<a href="	act\HARYANA STATE ACT\	24.The Factories (Haryana) Exempting Rules, 1980.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	27	</td><td>	The Factories (Haryana) Exempting Rules, 1987	</td><td>	<a href="	act\HARYANA STATE ACT\	25.The Factories (Haryana) Exempting Rules, 1987.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	28	</td><td>	Forest Rules	</td><td>	<a href="	act\HARYANA STATE ACT\	26.Forest Rules.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	29	</td><td>	Haryana (Prevention and Control of Water Pollution) Rules, 1978	</td><td>	<a href="	act\HARYANA STATE ACT\	27.Haryana (Prevention and Control of Water Pollution) Rules, 1978.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	30	</td><td>	The Haryana Accountability of Public Finances Act, 2019	</td><td>	<a href="	act\HARYANA STATE ACT\	28.The Haryana Accountability of Public Finances Act, 2019.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	31	</td><td>	Haryana Agricultural Credit Operations and Miscellaneous Provisions (Banks) Act, 1973	</td><td>	<a href="	act\HARYANA STATE ACT\	29.Haryana Agricultural Credit Operations and Miscellaneous Provisions (Banks) Act, 1973.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	32	</td><td>	Haryana Agricultural Produce Markets Act, 1961	</td><td>	<a href="	act\HARYANA STATE ACT\	30.Haryana Agricultural Produce Markets Act, 1961.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	33	</td><td>	Haryana Air (Prevention and Control of Pollution) Rules, 1983	</td><td>	<a href="	act\HARYANA STATE ACT\	31.Haryana Air (Prevention and Control of Pollution) Rules, 1983.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	34	</td><td>	The Haryana Anand Marriages Registration Rules, 2014	</td><td>	<a href="	act\HARYANA STATE ACT\	32.The Haryana Anand Marriages Registration Rules, 2014.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	35	</td><td>	The Haryana Anatomy Act, 1974	</td><td>	<a href="	act\HARYANA STATE ACT\	33.The Haryana Anatomy Act, 1974.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	36	</td><td>	The Haryana Animal (Registration, Certification and Breeding) Act, 2019	</td><td>	<a href="	act\HARYANA STATE ACT\	34.The Haryana Animal (Registration, Certification and Breeding) Act, 2019.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	37	</td><td>	The Haryana Apartment Ownership Act, 1983	</td><td>	<a href="	act\HARYANA STATE ACT\	35.The Haryana Apartment Ownership Act, 1983.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	38	</td><td>	Haryana Backward Classes (Reservation in Services and Admissions in Educational Institutions) Act, 2016	</td><td>	<a href="	act\HARYANA STATE ACT\	36.Haryana Backward Classes (Reservation in Services and Admissions in Educational Institutions) Act, 2016.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	39	</td><td>	The Haryana Board of School Education Act, 1969	</td><td>	<a href="	act\HARYANA STATE ACT\	37.The Haryana Board of School Education Act, 1969.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	40	</td><td>	The Haryana Canal and Drainage Act, 1974	</td><td>	<a href="	act\HARYANA STATE ACT\	38.The Haryana Canal and Drainage Act, 1974.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	41	</td><td>	The Haryana Ceiling of Land Holdings Act, 1972	</td><td>	<a href="	act\HARYANA STATE ACT\	39.The Haryana Ceiling of Land Holdings Act, 1972.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	42	</td><td>	Haryana Chit Funds Rules, 2018	</td><td>	<a href="	act\HARYANA STATE ACT\	40.Haryana Chit Funds Rules, 2018.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	43	</td><td>	The Haryana Clinical Establishments (Registration and Regulation) Act, 2014	</td><td>	<a href="	act\HARYANA STATE ACT\	41.The Haryana Clinical Establishments (Registration and Regulation) Act, 2014.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	44	</td><td>	The Haryana Clinical Establishments (Registration and Regulation) Adoption Act, 2018	</td><td>	<a href="	act\HARYANA STATE ACT\	42.The Haryana Clinical Establishments (Registration and Regulation) Adoption Act, 2018.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	45	</td><td>	The Haryana Clinical Establishments (Registration and Regulation) Rules, 2018	</td><td>	<a href="	act\HARYANA STATE ACT\	43.The Haryana Clinical Establishments (Registration and Regulation) Rules, 2018.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	46	</td><td>	Haryana Co-operative Societies Act, 1984	</td><td>	<a href="	act\HARYANA STATE ACT\	44.Haryana Co-operative Societies Act, 1984.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	47	</td><td>	The Haryana Common Purposes Land Eviction and Rent Recovery Act, 1985	</td><td>	<a href="	act\HARYANA STATE ACT\	45.The Haryana Common Purposes Land Eviction and Rent Recovery Act, 1985.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	48	</td><td>	The Haryana Conservation of Firewood Supplies (Restrictions on Transport) Order, 1973	</td><td>	<a href="	act\HARYANA STATE ACT\	46.The Haryana Conservation of Firewood Supplies (Restrictions on Transport) Order, 1973.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	49	</td><td>	Haryana Consumer Welfare Fund Rules, 2005	</td><td>	<a href="	act\HARYANA STATE ACT\	47.Haryana Consumer Welfare Fund Rules, 2005.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	50	</td><td>	The Haryana Contigency Fund Act, 1966	</td><td>	<a href="	act\HARYANA STATE ACT\	48.The Haryana Contigency Fund Act, 1966.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	51	</td><td>	Haryana Control of Bricks Supplies Order, 1972	</td><td>	<a href="	act\HARYANA STATE ACT\	49.Haryana Control of Bricks Supplies Order, 1972.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	52	</td><td>	Haryana Council of Homoeopathic System of Medicine Staff Regulations, 1996	</td><td>	<a href="	act\HARYANA STATE ACT\	50.Haryana Council of Homoeopathic System of Medicine Staff Regulations, 1996.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	53	</td><td>	Haryana Dangerous Machines (Regulation) Rules, 1987	</td><td>	<a href="	act\HARYANA STATE ACT\	51.Haryana Dangerous Machines (Regulation) Rules, 1987.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	54	</td><td>	Haryana Development and Regulation of Urban Areas (Amendment and Validation) Act, 2012	</td><td>	<a href="	act\HARYANA STATE ACT\	52.Haryana Development and Regulation of Urban Areas (Amendment and Validation) Act, 2012.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	55	</td><td>	The Haryana Development and Regulation of Urban Areas Act, 1975	</td><td>	<a href="	act\HARYANA STATE ACT\	53.The Haryana Development and Regulation of Urban Areas Act, 1975.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	56	</td><td>	Haryana District Mineral Foundation Trust Rules, 2016	</td><td>	<a href="	act\HARYANA STATE ACT\	54.Haryana District Mineral Foundation Trust Rules, 2016.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	57	</td><td>	Haryana Enterprises Promotion Act, 2016	</td><td>	<a href="	act\HARYANA STATE ACT\	55.Haryana Enterprises Promotion Act, 2016.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	58	</td><td>	Haryana Essential Services Maintenance Act, 1974	</td><td>	<a href="	act\HARYANA STATE ACT\	56.Haryana Essential Services Maintenance Act, 1974.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	59	</td><td>	Haryana Evacuee Properties (Management and Disposal) Act, 2008	</td><td>	<a href="	act\HARYANA STATE ACT\	57.Haryana Evacuee Properties (Management and Disposal) Act, 2008.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	60	</td><td>	Haryana Finance Commission Rules, 1994	</td><td>	<a href="	act\HARYANA STATE ACT\	58.Haryana Finance Commission Rules, 1994.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	61	</td><td>	Haryana Financial Commissioners' (Distribution of Business) Rules, 1975	</td><td>	<a href="	act\HARYANA STATE ACT\	59.Haryana Financial Commissioners' (Distribution of Business) Rules, 1975.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	62	</td><td>	Haryana Fire Service Act, 2009	</td><td>	<a href="	act\HARYANA STATE ACT\	60.Haryana Fire Service Act, 2009.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	63	</td><td>	Haryana Fiscal Responsibility and Budget Management Act, 2005	</td><td>	<a href="	act\HARYANA STATE ACT\	61.Haryana Fiscal Responsibility and Budget Management Act, 2005.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	64	</td><td>	Haryana Fisheries Rules, 1996	</td><td>	<a href="	act\HARYANA STATE ACT\	62.Haryana Fisheries Rules, 1996.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	65	</td><td>	Haryana Forest Development (Repeal) Act, 1986	</td><td>	<a href="	act\HARYANA STATE ACT\	63.Haryana Forest Development (Repeal) Act, 1986.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	66	</td><td>	Haryana Forest Development Act, 1983	</td><td>	<a href="	act\HARYANA STATE ACT\	64.Haryana Forest Development Act, 1983.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	67	</td><td>	Haryana Gauvansh Sanrakshan and Gausamvardhan Act, 2015	</td><td>	<a href="	act\HARYANA STATE ACT\	65.Haryana Gauvansh Sanrakshan and Gausamvardhan Act, 2015.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	68	</td><td>	The Haryana Goods and Services Tax Act, 2017	</td><td>	<a href="	act\HARYANA STATE ACT\	66.The Haryana Goods and Services Tax Act, 2017.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	69	</td><td>	Haryana Housing Board Act, 1971	</td><td>	<a href="	act\HARYANA STATE ACT\	67.Haryana Housing Board Act, 1971.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	70	</td><td>	The Haryana Industrial Estates (Development and Regulation) Act, 1974	</td><td>	<a href="	act\HARYANA STATE ACT\	68.The Haryana Industrial Estates (Development and Regulation) Act, 1974.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	71	</td><td>	Haryana Industrial Promotion Act, 2005	</td><td>	<a href="	act\HARYANA STATE ACT\	69.Haryana Industrial Promotion Act, 2005.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	72	</td><td>	Haryana Industry Facilitation Council (Arbitration) Rules, 2001	</td><td>	<a href="	act\HARYANA STATE ACT\	70.Haryana Industry Facilitation Council (Arbitration) Rules, 2001.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	73	</td><td>	Haryana Insecticides (Appeal) Rules, 1976	</td><td>	<a href="	act\HARYANA STATE ACT\	71.Haryana Insecticides (Appeal) Rules, 1976.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	74	</td><td>	The Haryana Kisan Kalyan Pradhikaran Act, 2018	</td><td>	<a href="	act\HARYANA STATE ACT\	72.The Haryana Kisan Kalyan Pradhikaran Act, 2018.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	75	</td><td>	The Haryana Land Holdings Tax (Repeal) Act, 1986	</td><td>	<a href="	act\HARYANA STATE ACT\	73.The Haryana Land Holdings Tax (Repeal) Act, 1986.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	76	</td><td>	HARYANA LAND REVENUE (ADDITIONAL SURCHARGE) ACT, 1969	</td><td>	<a href="	act\HARYANA STATE ACT\	74.HARYANA LAND REVENUE (ADDITIONAL SURCHARGE) ACT, 1969.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	77	</td><td>	Haryana Lifts and Escalators Act, 2008	</td><td>	<a href="	act\HARYANA STATE ACT\	75.Haryana Lifts and Escalators Act, 2008.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	78	</td><td>	 Haryana Local Area Development Tax Act, 2000	</td><td>	<a href="	act\HARYANA STATE ACT\	76. Haryana Local Area Development Tax Act, 2000.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	79	</td><td>	Haryana Maintenance of Parents and Senior Citizen Rules, 2009	</td><td>	<a href="	act\HARYANA STATE ACT\	77.Haryana Maintenance of Parents and Senior Citizen Rules, 2009.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	80	</td><td>	Haryana Management of Civic Amenities and Infrastructure Deficient Municipal Areas (Special Provisions) Act, 2016	</td><td>	<a href="	act\HARYANA STATE ACT\	78.Haryana Management of Civic Amenities and Infrastructure Deficient Municipal Areas (Special Provisions) Act, 2016.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	81	</td><td>	Haryana Minerals (Vesting of Rights) Act, 1973	</td><td>	<a href="	act\HARYANA STATE ACT\	79.Haryana Minerals (Vesting of Rights) Act, 1973.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	82	</td><td>	Haryana Motor Transport Vehicles (Toll) Act, 1991	</td><td>	<a href="	act\HARYANA STATE ACT\	80.Haryana Motor Transport Vehicles (Toll) Act, 1991.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	83	</td><td>	Haryana Motor Vehicles Rules, 1993	</td><td>	<a href="	act\HARYANA STATE ACT\	81.Haryana Motor Vehicles Rules, 1993.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	84	</td><td>	Haryana Motor Vehicles Taxation Act, 2016	</td><td>	<a href="	act\HARYANA STATE ACT\	82.Haryana Motor Vehicles Taxation Act, 2016.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	85	</td><td>	The Haryana Municipal Act, 1973	</td><td>	<a href="	act\HARYANA STATE ACT\	83.The Haryana Municipal Act, 1973.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	86	</td><td>	Haryana Municipal Citizens' Participation Act, 2008	</td><td>	<a href="	act\HARYANA STATE ACT\	84.Haryana Municipal Citizens' Participation Act, 2008.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	87	</td><td>	Haryana Municipal Common Lands (Regulation) Act, 1974	</td><td>	<a href="	act\HARYANA STATE ACT\	85.Haryana Municipal Common Lands (Regulation) Act, 1974.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	88	</td><td>	Haryana Municipal Corporation Act, 1994	</td><td>	<a href="	act\HARYANA STATE ACT\	86.Haryana Municipal Corporation Act, 1994.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	89	</td><td>	Haryana Municipal Entertainment Duty Act, 2019	</td><td>	<a href="	act\HARYANA STATE ACT\	87.Haryana Municipal Entertainment Duty Act, 2019.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	90	</td><td>	Haryana Municipal Street Vendors (Protection of Livelihood and Regulation of Street Vending) Act, 2014	</td><td>	<a href="	act\HARYANA STATE ACT\	88.Haryana Municipal Street Vendors (Protection of Livelihood and Regulation of Street Vending) Act, 2014.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	91	</td><td>	Haryana Municipality Public Disclosure Act, 2008	</td><td>	<a href="	act\HARYANA STATE ACT\	89.Haryana Municipality Public Disclosure Act, 2008.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	92	</td><td>	Haryana Murrah Buffalo and other Milch Animal Breed (Preservation and Development of Animal Husbandry and Dairy Development Sector) Act, 2001	</td><td>	<a href="	act\HARYANA STATE ACT\	90.Haryana Murrah Buffalo and other Milch Animal Breed (Preservation and Development of Animal Husbandry and Dairy Development Sector) Act, 2001.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	93	</td><td>	Haryana Narcotic Drugs and Psychotropic Substances Rules, 1985	</td><td>	<a href="	act\HARYANA STATE ACT\	91.Haryana Narcotic Drugs and Psychotropic Substances Rules, 1985.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	94	</td><td>	Haryana Non-Biodegradable Garbage (Control) Act, 1998	</td><td>	<a href="	act\HARYANA STATE ACT\	92.Haryana Non-Biodegradable Garbage (Control) Act, 1998.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	95	</td><td>	Haryana Pond and Waste Water Management Authority Act, 2018	</td><td>	<a href="	act\HARYANA STATE ACT\	93.Haryana Pond and Waste Water Management Authority Act, 2018.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	96	</td><td>	Haryana Prevention of Defacement of Property Act, 1989	</td><td>	<a href="	act\HARYANA STATE ACT\	94.Haryana Prevention of Defacement of Property Act, 1989.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	97	</td><td>	Haryana Private Educational Institutions (Taking Over of Management) Act, 1978	</td><td>	<a href="	act\HARYANA STATE ACT\	95.Haryana Private Educational Institutions (Taking Over of Management) Act, 1978.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	98	</td><td>	Haryana Private Health Sciences Educational Institutions (Regulation of Admission, Fixation of Fee and Maintenance of Educational Standards) Act, 2012	</td><td>	<a href="	act\HARYANA STATE ACT\	96.Haryana Private Health Sciences Educational Institutions (Regulation of Admission, Fixation of Fee and Maintenance of Educational Standards) Act, 2012.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	99	</td><td>	Haryana Private Security Agencies (Private Security to Cash Transportation Activities) Rules, 2019	</td><td>	<a href="	act\HARYANA STATE ACT\	97.Haryana Private Security Agencies (Private Security to Cash Transportation Activities) Rules, 2019.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	100	</td><td>	Haryana Private Technical Educational Institution (Regulation of Admission and Fee) Act, 2012	</td><td>	<a href="	act\HARYANA STATE ACT\	98.Haryana Private Technical Educational Institution (Regulation of Admission and Fee) Act, 2012.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	101	</td><td>	Haryana Private Universities, 2006	</td><td>	<a href="	act\HARYANA STATE ACT\	99.Haryana Private Universities, 2006.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	102	</td><td>	Haryana Protection of Interest of Depositors in Financial Establishment Act, 2013	</td><td>	<a href="	act\HARYANA STATE ACT\	100.Haryana Protection of Interest of Depositors in Financial Establishment Act, 2013.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	103	</td><td>	Haryana Public Distribution System (Licensing and Control) Order, 2002	</td><td>	<a href="	act\HARYANA STATE ACT\	101.Haryana Public Distribution System (Licensing and Control) Order, 2002.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	104	</td><td>	Haryana Public Libraries Act, 1989	</td><td>	<a href="	act\HARYANA STATE ACT\	102.Haryana Public Libraries Act, 1989.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	105	</td><td>	Haryana Public Money (Recovery of Dues) Act, 1979	</td><td>	<a href="	act\HARYANA STATE ACT\	103.Haryana Public Money (Recovery of Dues) Act, 1979.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	106	</td><td>	Haryana Public Premises and Land (Eviction and Rent Recovery) Act, 1972	</td><td>	<a href="	act\HARYANA STATE ACT\	104.Haryana Public Premises and Land (Eviction and Rent Recovery) Act, 1972.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	107	</td><td>	Haryana Public Wakfs (Extension of Limitation) Act, 1991	</td><td>	<a href="	act\HARYANA STATE ACT\	105.Haryana Public Wakfs (Extension of Limitation) Act, 1991.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	108	</td><td>	Haryana Real Estate (Regulation and Development) Rules, 2017	</td><td>	<a href="	act\HARYANA STATE ACT\	106.Haryana Real Estate (Regulation and Development) Rules, 2017.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	109	</td><td>	Haryana Registration and Regulation of Societies (Amendment) Act, 2014	</td><td>	<a href="	act\HARYANA STATE ACT\	107.Haryana Registration and Regulation of Societies (Amendment) Act, 2014.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	110	</td><td>	Haryana Registration and Regulation of Societies Act, 2012	</td><td>	<a href="	act\HARYANA STATE ACT\	108.Haryana Registration and Regulation of Societies Act, 2012.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	111	</td><td>	Haryana Registration of Births and Deaths Rules, 2002	</td><td>	<a href="	act\HARYANA STATE ACT\	109.Haryana Registration of Births and Deaths Rules, 2002.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	112	</td><td>	Haryana Regulation and Control of Crushers Act, 1991	</td><td>	<a href="	act\HARYANA STATE ACT\	110.Haryana Regulation and Control of Crushers Act, 1991.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	113	</td><td>	Haryana Relief of Agricultural Indebtedness Act, 1976	</td><td>	<a href="	act\HARYANA STATE ACT\	111.Haryana Relief of Agricultural Indebtedness Act, 1976.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	114	</td><td>	Haryana Relief of Agricultural Indebtedness Act, 1989	</td><td>	<a href="	act\HARYANA STATE ACT\	112.Haryana Relief of Agricultural Indebtedness Act, 1989.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	115	</td><td>	Haryana Requisitioning and Acquisition of Immovable Property Act, 1973	</td><td>	<a href="	act\HARYANA STATE ACT\	113.Haryana Requisitioning and Acquisition of Immovable Property Act, 1973.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	116	</td><td>	Haryana Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement Rules, 2017	</td><td>	<a href="	act\HARYANA STATE ACT\	114.Haryana Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement Rules, 2017.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	117	</td><td>	Haryana Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement Rules, 2018	</td><td>	<a href="	act\HARYANA STATE ACT\	115.Haryana Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement Rules, 2018.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	118	</td><td>	Haryana Right to Information Rules, 2005	</td><td>	<a href="	act\HARYANA STATE ACT\	116.Haryana Right to Information Rules, 2005.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	119	</td><td>	  The Haryana Right to Service Act, 2014	</td><td>	<a href="	act\HARYANA STATE ACT\	117.  The Haryana Right to Service Act, 2014.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	120	</td><td>	 The Haryana Road Infrastructure Protection Act, 2017	</td><td>	<a href="	act\HARYANA STATE ACT\	118. The Haryana Road Infrastructure Protection Act, 2017.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	121	</td><td>	 The Haryana Rural Development Act, 1986	</td><td>	<a href="	act\HARYANA STATE ACT\	119. The Haryana Rural Development Act, 1986.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	122	</td><td>	 The Haryana Rural Development Fund Act, 1983	</td><td>	<a href="	act\HARYANA STATE ACT\	120. The Haryana Rural Development Fund Act, 1983.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	123	</td><td>	 Haryana Rural Employment Guarantee Scheme, 2007	</td><td>	<a href="	act\HARYANA STATE ACT\	121. Haryana Rural Employment Guarantee Scheme, 2007.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	124	</td><td>	 The Haryana Rural Sanitation Board Act, 1972	</td><td>	<a href="	act\HARYANA STATE ACT\	122. The Haryana Rural Sanitation Board Act, 1972.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	125	</td><td>	 The Haryana School Education Act, 1995	</td><td>	<a href="	act\HARYANA STATE ACT\	123. The Haryana School Education Act, 1995.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	126	</td><td>	 The Haryana Settlement of Outstanding Dues Act, 2017	</td><td>	<a href="	act\HARYANA STATE ACT\	124. The Haryana Settlement of Outstanding Dues Act, 2017.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	127	</td><td>	 The Haryana Shri Mata Mansa Devi Shrine Act, 1991	</td><td>	<a href="	act\HARYANA STATE ACT\	125. The Haryana Shri Mata Mansa Devi Shrine Act, 1991.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	128	</td><td>	 The Haryana Shri Mata Sheetla Devi Shrine Act, 1991	</td><td>	<a href="	act\HARYANA STATE ACT\	126. The Haryana Shri Mata Sheetla Devi Shrine Act, 1991.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	129	</td><td>	 The Haryana Sikh Gurdwara (Management) Act, 2014	</td><td>	<a href="	act\HARYANA STATE ACT\	127. The Haryana Sikh Gurdwara (Management) Act, 2014.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	130	</td><td>	 The Haryana Special Economic Zone Act, 2005	</td><td>	<a href="	act\HARYANA STATE ACT\	128. The Haryana Special Economic Zone Act, 2005.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	131	</td><td>	 Haryana Stamp (Payment of Duties by Means of Special Adhesive Stamps) Rules, 1988	</td><td>	<a href="	act\HARYANA STATE ACT\	129. Haryana Stamp (Payment of Duties by Means of Special Adhesive Stamps) Rules, 1988.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	132	</td><td>	 Haryana Stamp (Prevention of Undervaluation of Instruments) Rules, 1978	</td><td>	<a href="	act\HARYANA STATE ACT\	130. Haryana Stamp (Prevention of Undervaluation of Instruments) Rules, 1978.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	133	</td><td>	 The Haryana State Higher Education Council Act, 2018	</td><td>	<a href="	act\HARYANA STATE ACT\	131. The Haryana State Higher Education Council Act, 2018.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	134	</td><td>	 The Haryana State Legal Service Authority Rules, 1995	</td><td>	<a href="	act\HARYANA STATE ACT\	132. The Haryana State Legal Service Authority Rules, 1995.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	135	</td><td>	 The Haryana State Legislature (Prevention of Disqualification) Act, 1974	</td><td>	<a href="	act\HARYANA STATE ACT\	133. The Haryana State Legislature (Prevention of Disqualification) Act, 1974.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	136	</td><td>	 Haryana State University of Horticultural Sciences, Karnal Act, 2015	</td><td>	<a href="	act\HARYANA STATE ACT\	134. Haryana State University of Horticultural Sciences, Karnal Act, 2015.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	137	</td><td>	 Haryana Tax on Entry of Goods Into Local Areas Act, 2008	</td><td>	<a href="	act\HARYANA STATE ACT\	135. Haryana Tax on Entry of Goods Into Local Areas Act, 2008.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	138	</td><td>	 Haryana Tax on Luxuries Act, 1994	</td><td>	<a href="	act\HARYANA STATE ACT\	136. Haryana Tax on Luxuries Act, 1994.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	139	</td><td>	 Haryana Underground Pipelines (Acquisition of Right of User In Land) Act, 2008	</td><td>	<a href="	act\HARYANA STATE ACT\	137. Haryana Underground Pipelines (Acquisition of Right of User In Land) Act, 2008.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	140	</td><td>	 Haryana Urban (Control of Rent and Eviction) Act, 1973	</td><td>	<a href="	act\HARYANA STATE ACT\	138. Haryana Urban (Control of Rent and Eviction) Act, 1973.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	141	</td><td>	 Haryana Shehri Vikas Pradhikaran Act, 1977	</td><td>	<a href="	act\HARYANA STATE ACT\	139. Haryana Shehri Vikas Pradhikaran Act, 1977.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	142	</td><td>	 Hindu Marriage (Punjab) Registration Rules, 1960	</td><td>	<a href="	act\HARYANA STATE ACT\	140. Hindu Marriage (Punjab) Registration Rules, 1960.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	143	</td><td>	 The Indian Easements(1961)	</td><td>	<a href="	act\HARYANA STATE ACT\	141. The Indian Easements(1961).pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	144	</td><td>	 The Indian Electricity(1975)	</td><td>	<a href="	act\HARYANA STATE ACT\	142. The Indian Electricity(1975).pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	145	</td><td>	 The Indian Electricity (1987)	</td><td>	<a href="	act\HARYANA STATE ACT\	143. The Indian Electricity (1987).pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	146	</td><td>	 The Indian Electricity (1998)	</td><td>	<a href="	act\HARYANA STATE ACT\	144. The Indian Electricity (1998).pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	147	</td><td>	 The Indian Forest (1948)	</td><td>	<a href="	act\HARYANA STATE ACT\	145. The Indian Forest (1948).pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	148	</td><td>	 Indian Forest ACT (1973)	</td><td>	<a href="	act\HARYANA STATE ACT\	146. Indian Forest ACT (1973).pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	149	</td><td>	 Indian Forest second amendement act 1973	</td><td>	<a href="	act\HARYANA STATE ACT\	147. Indian Forest second amendement act 1973.docx.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	150	</td><td>	 The Indian Forest 1954	</td><td>	<a href="	act\HARYANA STATE ACT\	148. The Indian Forest 1954.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	151	</td><td>	 The Indian Forest 1962	</td><td>	<a href="	act\HARYANA STATE ACT\	149. The Indian Forest 1962.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	152	</td><td>	 The Indian Stamp (Haryana Amendment) Act, 2018	</td><td>	<a href="	act\HARYANA STATE ACT\	151. The Indian Stamp (Haryana Amendment) Act, 2018.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	153	</td><td>	 The Indian Stamp Rules, 1925	</td><td>	<a href="	act\HARYANA STATE ACT\	152. The Indian Stamp Rules, 1925.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	154	</td><td>	 The Industrial Disputes (Amendment and Miscellaneous Provisions) (Punjab Amendment) Act, 1957	</td><td>	<a href="	act\HARYANA STATE ACT\	153. The Industrial Disputes (Amendment and Miscellaneous Provisions) (Punjab Amendment) Act, 1957.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	155	</td><td>	 The Industrial Disputes (Haryana Amendment) Act, 1976	</td><td>	<a href="	act\HARYANA STATE ACT\	154. The Industrial Disputes (Haryana Amendment) Act, 1976.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	156	</td><td>	 The Industrial Disputes (Punjab Amendment) Act, 1957	</td><td>	<a href="	act\HARYANA STATE ACT\	155. The Industrial Disputes (Punjab Amendment) Act, 1957.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	157	</td><td>	 Industrial Disputes (Punjab) Rules, 1958	</td><td>	<a href="	act\HARYANA STATE ACT\	156. Industrial Disputes (Punjab) Rules, 1958.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	158	</td><td>	 Land Acquisition (Companies) Rules, 1963	</td><td>	<a href="	act\HARYANA STATE ACT\	157. Land Acquisition (Companies) Rules, 1963.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	159	</td><td>	 The Land Acquisition (East Punjab) Amendment Act, 1948	</td><td>	<a href="	act\HARYANA STATE ACT\	158. The Land Acquisition (East Punjab) Amendment Act, 1948.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	160	</td><td>	 The Land Acquisition (Punjab Amendment) Act, 1953	</td><td>	<a href="	act\HARYANA STATE ACT\	159. The Land Acquisition (Punjab Amendment) Act, 1953.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	161	</td><td>	 The Land Acquisition (Punjab Amendment) Act, 1956	</td><td>	<a href="	act\HARYANA STATE ACT\	160. The Land Acquisition (Punjab Amendment) Act, 1956.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	162	</td><td>	 The Land Acquisition (Punjab Amendment) Act, 1962	</td><td>	<a href="	act\HARYANA STATE ACT\	161. The Land Acquisition (Punjab Amendment) Act, 1962.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	163	</td><td>	 The Land Acquisition Punjab Second Amendment Act, 1956	</td><td>	<a href="	act\HARYANA STATE ACT\	162. The Land Acquisition Punjab Second Amendment Act, 1956.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	164	</td><td>	 The Land Improvement Loans Act, 1883	</td><td>	<a href="	act\HARYANA STATE ACT\	163. The Land Improvement Loans Act, 1883.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	165	</td><td>	 Land Revenue Assessment Rules, 1929	</td><td>	<a href="	act\HARYANA STATE ACT\	164. Land Revenue Assessment Rules, 1929.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	166	</td><td>	 The Local Authorities Loans (East Punjab Amendment) Act, 1949	</td><td>	<a href="	act\HARYANA STATE ACT\	165. The Local Authorities Loans (East Punjab Amendment) Act, 1949.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	167	</td><td>	 The Local Authorities Loans Act, 1914	</td><td>	<a href="	act\HARYANA STATE ACT\	166. The Local Authorities Loans Act, 1914.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	168	</td><td>	 The Municipal Account Code, 1930	</td><td>	<a href="	act\HARYANA STATE ACT\	167. The Municipal Account Code, 1930.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	169	</td><td>	 Municipal General (Haryana Repeal) Rules, 1991	</td><td>	<a href="	act\HARYANA STATE ACT\	168. Municipal General (Haryana Repeal) Rules, 1991.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	170	</td><td>	 The Payment of Wages (Haryana Amendment) Act, 1985	</td><td>	<a href="	act\HARYANA STATE ACT\	169. The Payment of Wages (Haryana Amendment) Act, 1985.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	171	</td><td>	 The Payment of Wages (Punjab Amendment) Act, 1962	</td><td>	<a href="	act\HARYANA STATE ACT\	170. The Payment of Wages (Punjab Amendment) Act, 1962.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	172	</td><td>	 The Payment of Wages (Punjab Amendment) Act, 1964	</td><td>	<a href="	act\HARYANA STATE ACT\	171. The Payment of Wages (Punjab Amendment) Act, 1964.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	173	</td><td>	 Policy Regarding Acquisition of Land for Private Development and in Public Private Partnership for setting up of Special Economic Zones, Technology Cities, Industrial Parks and Industrial Model Townships	</td><td>	<a href="	act\HARYANA STATE ACT\	172. Policy Regarding Acquisition of Land for Private Development and in Public Private Partnership for setting up of Special Economic Zones, Technology Cities, Industrial Parks and Industrial Model Townships.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	174	</td><td>	 The Press and Registration of Books (Punjab Amendment) Act, 1942	</td><td>	<a href="	act\HARYANA STATE ACT\	174. The Press and Registration of Books (Punjab Amendment) Act, 1942.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	175	</td><td>	 The Press and Registration of Books (Punjab Amendment) Act, 1957	</td><td>	<a href="	act\HARYANA STATE ACT\	175. The Press and Registration of Books (Punjab Amendment) Act, 1957.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	176	</td><td>	 The Provincial Insolvency (Punjab Amendment) Act, 1939	</td><td>	<a href="	act\HARYANA STATE ACT\	176. The Provincial Insolvency (Punjab Amendment) Act, 1939.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	177	</td><td>	The Punjab Ayurvedic and Unani Practitioners (Haryana Amendment) Act, 2014	</td><td>	<a href="	act\HARYANA STATE ACT\	177.The Punjab Ayurvedic and Unani Practitioners (Haryana Amendment) Act, 2014.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	178	</td><td>	The Punjab Ayurvedic and Unani Practitioners Act, 1963	</td><td>	<a href="	act\HARYANA STATE ACT\	178.The Punjab Ayurvedic and Unani Practitioners Act, 1963.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	179	</td><td>	The Punjab Chemical Works Rules, 1933	</td><td>	<a href="	act\HARYANA STATE ACT\	179.The Punjab Chemical Works Rules, 1933.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	180	</td><td>	Punjab Colonisation of Government Lands (Punjab) Act, 1912	</td><td>	<a href="	act\HARYANA STATE ACT\	180.Punjab Colonisation of Government Lands (Punjab) Act, 1912.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	181	</td><td>	The Punjab Compulsory Service Act, 1961	</td><td>	<a href="	act\HARYANA STATE ACT\	181.The Punjab Compulsory Service Act, 1961.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	182	</td><td>	The Punjab Consolidation of Land Proceedings (Validation) Act, 1957	</td><td>	<a href="	act\HARYANA STATE ACT\	182.The Punjab Consolidation of Land Proceedings (Validation) Act, 1957.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	183	</td><td>	The Punjab Copying Fees Act, 1936	</td><td>	<a href="	act\HARYANA STATE ACT\	183.The Punjab Copying Fees Act, 1936.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	184	</td><td>	The Punjab Cotton Ginning and Pressing Factories Act, 1953	</td><td>	<a href="	act\HARYANA STATE ACT\	184.The Punjab Cotton Ginning and Pressing Factories Act, 1953.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	185	</td><td>	The Punjab Custom (Power to Contest) Act, 1920	</td><td>	<a href="	act\HARYANA STATE ACT\	185.The Punjab Custom (Power to Contest) Act, 1920.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	186	</td><td>	The Punjab Debt Conciliation Board (Custody and Preservation of Records) Rules, 1935	</td><td>	<a href="	act\HARYANA STATE ACT\	186.The Punjab Debt Conciliation Board (Custody and Preservation of Records) Rules, 1935.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	187	</td><td>	The Punjab Debt Conciliation Rules, 1935	</td><td>	<a href="	act\HARYANA STATE ACT\	187.The Punjab Debt Conciliation Rules, 1935.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	188	</td><td>	The Punjab Debtors' Protection Act, 1936	</td><td>	<a href="	act\HARYANA STATE ACT\	188.The Punjab Debtors' Protection Act, 1936.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	189	</td><td>	The Punjab Electricity (Duty) Act, 1958	</td><td>	<a href="	act\HARYANA STATE ACT\	189.The Punjab Electricity (Duty) Act, 1958.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	190	</td><td>	The Punjab Electricity (Emergency Powers) Act, 1941	</td><td>	<a href="	act\HARYANA STATE ACT\	190.The Punjab Electricity (Emergency Powers) Act, 1941.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	191	</td><td>	Punjab Excise (Haryana Validation) Act, 2019	</td><td>	<a href="	act\HARYANA STATE ACT\	191.Punjab Excise (Haryana Validation) Act, 2019.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	192	</td><td>	The Punjab Excise Act, 1914	</td><td>	<a href="	act\HARYANA STATE ACT\	192.The Punjab Excise Act, 1914.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	193	</td><td>	The Punjab Factories (Control of Dismantling) Rules, 1950	</td><td>	<a href="	act\HARYANA STATE ACT\	193.The Punjab Factories (Control of Dismantling) Rules, 1950.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	194	</td><td>	The Punjab Fisheries Act, 1914	</td><td>	<a href="	act\HARYANA STATE ACT\	194.The Punjab Fisheries Act, 1914.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	195	</td><td>	The Punjab Forest (Sale of Timber) Act, 1913	</td><td>	<a href="	act\HARYANA STATE ACT\	195.The Punjab Forest (Sale of Timber) Act, 1913.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	196	</td><td>	The Punjab Improved Seeds and Seedlings Rules, 1950	</td><td>	<a href="	act\HARYANA STATE ACT\	196.The Punjab Improved Seeds and Seedlings Rules, 1950.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	197	</td><td>	The Punjab Khadi and Village Industries Board Act, 1955	</td><td>	<a href="	act\HARYANA STATE ACT\	197.The Punjab Khadi and Village Industries Board Act, 1955.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	198	</td><td>	The Punjab Land Improvement Schemes Act, 1963	</td><td>	<a href="	act\HARYANA STATE ACT\	198.The Punjab Land Improvement Schemes Act, 1963.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	199	</td><td>	The Punjab Land Preservation Act, 1900	</td><td>	<a href="	act\HARYANA STATE ACT\	199.The Punjab Land Preservation Act, 1900.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	200	</td><td>	The Punjab Land Revenue (Special Assessments) Act, 1955	</td><td>	<a href="	act\HARYANA STATE ACT\	200.The Punjab Land Revenue (Special Assessments) Act, 1955.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	201	</td><td>	The Punjab Land Revenue (Special Assessments) Amendment and Validation Act, 1963	</td><td>	<a href="	act\HARYANA STATE ACT\	201.The Punjab Land Revenue (Special Assessments) Amendment and Validation Act, 1963.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	202	</td><td>	The Punjab Land Revenue (Special Charges) Act, 1958	</td><td>	<a href="	act\HARYANA STATE ACT\	202.The Punjab Land Revenue (Special Charges) Act, 1958.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	203	</td><td>	The Punjab Land Revenue Act, 1887	</td><td>	<a href="	act\HARYANA STATE ACT\	203.The Punjab Land Revenue Act, 1887.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	204	</td><td>	The Punjab Land Revenue Special Assessment (Exemption) Act, 1962	</td><td>	<a href="	act\HARYANA STATE ACT\	204.The Punjab Land Revenue Special Assessment (Exemption) Act, 1962.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	205	</td><td>	The Punjab Laws (Application) Act, 1957	</td><td>	<a href="	act\HARYANA STATE ACT\	205.The Punjab Laws (Application) Act, 1957.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	206	</td><td>	The Punjab Laws (Application) Act, 1966	</td><td>	<a href="	act\HARYANA STATE ACT\	206.The Punjab Laws (Application) Act, 1966.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	207	</td><td>	The Punjab Local Authorities (Aided Schools) Act, 1959	</td><td>	<a href="	act\HARYANA STATE ACT\	207.The Punjab Local Authorities (Aided Schools) Act, 1959.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	208	</td><td>	The Punjab Non-Trading Companies Act, 1960	</td><td>	<a href="	act\HARYANA STATE ACT\	208.The Punjab Non-Trading Companies Act, 1960.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	209	</td><td>	The Punjab Passengers and Goods Taxation Act, 1952	</td><td>	<a href="	act\HARYANA STATE ACT\	209.The Punjab Passengers and Goods Taxation Act, 1952.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	210	</td><td>	The Punjab Payment of Wages Rules, 1937	</td><td>	<a href="	act\HARYANA STATE ACT\	210.The Punjab Payment of Wages Rules, 1937.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	211	</td><td>	The Punjab Registration of Money-lender's Act, 1938	</td><td>	<a href="	act\HARYANA STATE ACT\	211.The Punjab Registration of Money-lender's Act, 1938.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	212	</td><td>	The Punjab Regulation of Accounts Act, 1930	</td><td>	<a href="	act\HARYANA STATE ACT\	212.The Punjab Regulation of Accounts Act, 1930.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	213	</td><td>	The Punjab Shops and Commercial Establishments Act, 1958	</td><td>	<a href="	act\HARYANA STATE ACT\	213.The Punjab Shops and Commercial Establishments Act, 1958.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	214	</td><td>	The Punjab Tenancy (East Punjab Validation of Orders, Proceedings and Acts) Act, 1948	</td><td>	<a href="	act\HARYANA STATE ACT\	214.The Punjab Tenancy (East Punjab Validation of Orders, Proceedings and Acts) Act, 1948.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	215	</td><td>	The Punjab Tenancy Act, 1887	</td><td>	<a href="	act\HARYANA STATE ACT\	215.The Punjab Tenancy Act, 1887.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	216	</td><td>	Punjab Urban Estates (Sale of Sites) Rules, 1965	</td><td>	<a href="	act\HARYANA STATE ACT\	216.Punjab Urban Estates (Sale of Sites) Rules, 1965.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	217	</td><td>	The Revenue Recovery Act, 1890	</td><td>	<a href="	act\HARYANA STATE ACT\	217.The Revenue Recovery Act, 1890.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	218	</td><td>	The Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement (Haryana Amendment) Act, 2017	</td><td>	<a href="	act\HARYANA STATE ACT\	218.The Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement (Haryana Amendment) Act, 2017.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>
<tr><td>	219	</td><td>	The Societies Registration Act, 1860	</td><td>	<a href="	act\HARYANA STATE ACT\	219.The Societies Registration Act, 1860.pdf	" target="_blank"	style="  background-color: green;  color: white;  padding: 4px 15px; text-align: center;   text-decoration: none; display: inline-block;">Download</td></tr>



</table>
<?php include("footer.php"); ?>