<?php include("main.php"); ?><div style="padding:20px">

<div class="easy-breadcrumb"><a href="/" class="easy-breadcrumb_segment easy-breadcrumb_segment-front">Home</a><span class="easy-breadcrumb_segment-separator"> ›› </span><a href="our_service.php">Our Services</a><span class="easy-breadcrumb_segment-separator"> ›› </span><a href="#">Societies under The Haryana Registration and Regulation
</a></div><br>
<br>
<p style="text-align: center;"><span style="color: #ff0000; font-size:27px"><strong>Societies Act, 2012</strong></span></p> <p align="left">&nbsp;</p> <table class="end" border="1" cellspacing="0" cellpadding="0"> <tbody>  <tr>
    <th width="10%" ><span>Sr. No</span></th>
    <th width="50%" ><span> Title</span></th>
	<th width="20%" ><span>   Download </span>   </th>
  </tr> <tr><td>1. </td> <td valign="top" width="433">Societies under The Haryana Registration and Regulation of Societies &nbsp;Act, 2012</td> <td valign="top" width="174"> <p align="center"><strong><a href="pdf/Haryana Registration and Regulation of Societies Act.pdf">DOWNLOAD</a></strong></p> </td> </tr> 
<tr> <td>2. </td><td valign="top" width="433">Haryana Registration and Regulation of Societies Rules, 2012</td> <td valign="top" width="174"> <p align="center"><strong><a href="pdf/Haryana Registration and Regulation of Societies Rules.pdf">DOWNLOAD</a></strong></p> </td> </tr></tbody> </table> <p>&nbsp;</p> <p class="Default">&nbsp;</p> <p class="Default">&nbsp;</p> <p class="Default"><span style="color: #ff0000;"><strong>CONTACT US</strong></span></p> <p class="Default"><span>K.BEHARI &amp; ASSOCIATES</span></p> <p class="Default"><span>[Project Consultants]</span></p> <p class="Default"><span>Kunj Behari Mahipal</span></p> <p class="Default"><span>C.Shekhar Mahipal (B.Com, LL.B Advocate)</span></p> <p class="Default"><span>ANAND SHANKER &amp; COMPANY</span></p> <p class="Default"><span>[Chartered Accountants]</span></p> <p class="Default"><span>CA. Anand Shanker Mahipal</span></p> <p class="Default"><span>&nbsp;</span></p> <p class="Default"><span style="color: #ff0000;"><strong>Contact Info:</strong></span></p> <p class="Default"><span>Mailing Address:</span></p> <p class="Default"><span>&ldquo;DGM Building&rdquo; Old Court Road, Near Railway Crossing SIRSA-125055 (HARYANA) INDIA</span></p> <p class="Default"><span><em>Phones &amp; Mobiles:&nbsp;</em>Phone: +91(1666) 232543, 234565, 234022 Mobile: +91-9416-351-167, 9050-902-425</span></p> <p class="Default"><span><em>Emails:</em></span></p> <p class="Default"><span>Kboffice.india@gmail.com</span></p> <p class="Default"><span>kbaconsultants@hotmail.com</span></p> <p><span>ca.anand@hotmail.com</span></p><div class="clearfix"> </div>
	<!--/footer-->
	<?php include("footer.php"); ?>